-- Generated by scripts/module-data.mjs.
-- Do not edit by hand; change module.ts and run npm run data:generate.
-- Module: hello
-- Schema hash: 974e3abe5c9c6738b086250154f10236c1a3d1c63ae9451192d1a09c28c5448b

create extension if not exists pgcrypto;

create table if not exists public.module_documents (
  id uuid primary key default gen_random_uuid(),
  product_id text not null,
  module_id text not null,
  scope_type text not null,
  scope_id text,
  document_name text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by text,
  updated_by text
);

create index if not exists module_documents__module_document_scope_idx
  on public.module_documents (product_id, module_id, document_name, scope_type, scope_id);

alter table public.module_documents enable row level security;
alter table public.module_documents force row level security;

drop policy if exists module_documents__module_scope_policy on public.module_documents;
create policy module_documents__module_scope_policy
  on public.module_documents
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = current_setting('ploykit.module_id', true)
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = current_setting('ploykit.module_id', true)
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );

create table if not exists public.module_data_models (
  module_id text not null,
  model_kind text not null,
  model_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, model_kind, model_name)
);

create table if not exists public.module_data_migrations (
  module_id text primary key,
  data_version integer not null,
  migration_mode text not null,
  migration_dir text not null,
  schema_hash text not null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.module_data_grants (
  module_id text not null,
  grant_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, grant_name)
);

create table if not exists public.module_data_checks (
  module_id text not null,
  check_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, check_name)
);

insert into public.module_data_migrations
  (module_id, data_version, migration_mode, migration_dir, schema_hash)
values
  ('hello', 1, 'generated', './migrations', '974e3abe5c9c6738b086250154f10236c1a3d1c63ae9451192d1a09c28c5448b')
on conflict (module_id)
do update set
  data_version = excluded.data_version,
  migration_mode = excluded.migration_mode,
  migration_dir = excluded.migration_dir,
  schema_hash = excluded.schema_hash,
  updated_at = now();

insert into public.module_data_models
  (module_id, model_kind, model_name, schema_hash, definition)
values
  ('hello', 'document', 'hello_messages', 'aa1e1728508d05fc6b602ec3979b746cc0d2bd71b9e7419df58df291078b33b6', '{"name":"hello_messages","scope":"user","fields":{"message":{"type":"string","required":true,"maxLength":200}}}'::jsonb),
  ('hello', 'table', 'hello_posts', 'e6f397c23ae12baaeee857f671c7d710d9ddab20b59c91b8bb8262d20f5792cd', '{"name":"hello_posts","physicalName":"mod_hello__hello_posts","scope":"public-read","columns":{"title":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"status":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"draft"},"metadata":{"kind":"jsonb","nullable":false,"primaryKey":false,"defaultRandom":false,"default":{"featured":false}},"published_at":{"kind":"timestamp","nullable":true,"primaryKey":false,"defaultRandom":false}},"unique":[["title"]],"indexes":[["status"],["published_at"]]}'::jsonb)
on conflict (module_id, model_kind, model_name)
do update set
  schema_hash = excluded.schema_hash,
  definition = excluded.definition,
  updated_at = now();

delete from public.module_data_grants where module_id = 'hello';
delete from public.module_data_checks where module_id = 'hello';

create table if not exists public."mod_hello__hello_posts" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "title" text not null,
  "status" text not null default 'draft',
  "metadata" jsonb not null default '{"featured":false}'::jsonb,
  "published_at" timestamptz
);

alter table public."mod_hello__hello_posts" enable row level security;
alter table public."mod_hello__hello_posts" force row level security;

create unique index if not exists "mod_hello__hello_posts__uniq_title"
  on public."mod_hello__hello_posts" ("title");

create index if not exists "mod_hello__hello_posts__idx_status"
  on public."mod_hello__hello_posts" ("status");

create index if not exists "mod_hello__hello_posts__idx_published_at"
  on public."mod_hello__hello_posts" ("published_at");

drop policy if exists "mod_hello__hello_posts__module_scope_policy" on public."mod_hello__hello_posts";
create policy "mod_hello__hello_posts__module_scope_policy"
  on public."mod_hello__hello_posts"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'hello'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'hello'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );
