/**
 *
 *
 * - EmailVerification
 * - PasswordReset
 * - Session Admin
 *
 * - entitlementAdmin Use user_entitlements (src/lib/services/user-entitlement-service.ts)
 */

import { betterAuth } from 'better-auth';
import { drizzleAdapter } from 'better-auth/adapters/drizzle';
import { createAuthMiddleware } from 'better-auth/api';
import { db } from '@/lib/db/client.server';
import { logger } from '@/lib/_core/logger';
import { env } from '@/lib/_core/env';
import { user, session, account } from '@/lib/db/schema';
import { eq } from 'drizzle-orm';
import { ensureUserInitialized, type UserInitializationSource } from './user-initialization.server';

function isDefinedOrigin(origin: string | undefined): origin is string {
  return Boolean(origin);
}

function getTrustedOrigins(): string[] {
  return Array.from(
    new Set([env.NEXT_PUBLIC_APP_URL, env.BETTER_AUTH_URL].filter(isDefinedOrigin))
  );
}

function shouldUseSecureCookies(): boolean {
  const baseUrl = env.BETTER_AUTH_URL ?? env.NEXT_PUBLIC_APP_URL;

  if (!baseUrl) {
    return env.NODE_ENV === 'production';
  }

  try {
    return new URL(baseUrl).protocol === 'https:';
  } catch {
    return env.NODE_ENV === 'production';
  }
}

function maskEmail(email: string): string {
  const [localPart, domain] = email.split('@');

  if (!localPart || !domain) {
    return '[invalid-email]';
  }

  const visiblePrefix = localPart.slice(0, 2);
  return `${visiblePrefix}${'*'.repeat(Math.max(1, localPart.length - 2))}@${domain}`;
}

/**
 * Registration source types
 */
/**
 * Detect registration source from request path
 *
 * @param path - The request path (e.g., '/sign-up/email', '/callback/google')
 * @returns The detected registration source
 */
function detectRegistrationSource(path: string): UserInitializationSource {
  if (path.includes('/callback/google') || path.includes('/google')) {
    return 'google';
  }
  if (path.includes('/callback/github') || path.includes('/github')) {
    return 'github';
  }
  return 'email';
}

/**
 * Clean up failed registration with retry mechanism
 *
 * Attempts to delete user records up to maxRetries times.
 * This ensures we don't leave orphaned records in the database.
 *
 * @param userId - The user ID to clean up
 * @param email - The user email (for logging)
 * @param maxRetries - Maximum number of retry attempts (default: 3)
 */
async function cleanupFailedRegistration(
  userId: string,
  email: string,
  maxRetries = 3
): Promise<void> {
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      await db.transaction(async (tx) => {
        // Delete in correct order to respect foreign key constraints
        await tx.delete(session).where(eq(session.userId, userId));
        await tx.delete(account).where(eq(account.userId, userId));
        await tx.delete(user).where(eq(user.id, userId));
      });

      logger.info({ userId, attempt }, 'User record cleaned up successfully');
      return;
    } catch (error) {
      logger.warn(
        { userId, email, attempt, error },
        `Cleanup attempt ${attempt}/${maxRetries} failed`
      );

      if (attempt === maxRetries) {
        logger.error(
          { userId, email, attempts: maxRetries },
          'All cleanup attempts failed - manual intervention required'
        );
      }
    }
  }
}

/**
 * Better Auth Instance
 *
 *
 * Note
 */
export const auth = betterAuth({
  database: drizzleAdapter(db, {
    provider: 'pg', // PostgreSQL
    // - session: userSession
    // - verification: EmailVerification token
  }),

  // EmailPasswordAuthentication

  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    maxPasswordLength: 128,
    resetPasswordTokenExpiresIn: 60 * 60,
    revokeSessionsOnPasswordReset: true,
    async sendResetPassword({ user, url }, request) {
      const maskedEmail = maskEmail(user.email);
      const delivery = env.AUTH_PASSWORD_RESET_DELIVERY ?? 'disabled';

      if (delivery !== 'log') {
        logger.error(
          {
            email: maskedEmail,
            hasRequest: Boolean(request),
            delivery,
          },
          'Password reset email provider is not configured'
        );
        throw new Error('Password reset email provider is not configured');
      }

      logger.warn(
        {
          email: maskedEmail,
          resetUrl: url,
        },
        'Password reset link generated by development delivery'
      );
    },
    async onPasswordReset({ user }) {
      logger.info(
        {
          userId: user.id,
          email: maskEmail(user.email),
        },
        'User password reset completed'
      );
    },
  },

  // Session Configuration

  session: {
    expiresIn: 60 * 60 * 24 * 30, // 30 days
    updateAge: 60 * 60 * 24, // 24 hours
    cookieCache: {
      enabled: false,
      maxAge: 60 * 5, // 5 minutes
    },
  },

  socialProviders: {
    // Google OAuth
    google: {
      clientId: env.GOOGLE_CLIENT_ID || '',
      clientSecret: env.GOOGLE_CLIENT_SECRET || '',
      enabled: !!(env.GOOGLE_CLIENT_ID && env.GOOGLE_CLIENT_SECRET),
    },
    // GitHub OAuth
    github: {
      clientId: env.GITHUB_CLIENT_ID || '',
      clientSecret: env.GITHUB_CLIENT_SECRET || '',
      enabled: !!(env.GITHUB_CLIENT_ID && env.GITHUB_CLIENT_SECRET),
    },
  },

  // Configuration

  plugins: [
    // - Schema: src/lib/db/schema/rbac.ts (roles, user_roles)
    // - Service: src/lib/auth/permissions.ts
    // - Schema: src/lib/db/schema/entitlement.ts (user_entitlements)
    // - Service: src/lib/services/user-entitlement-service.ts
  ],

  // Configuration

  secret: env.BETTER_AUTH_SECRET || env.AUTH_SECRET,

  // CORS
  trustedOrigins: getTrustedOrigins(),

  // URL
  baseURL: env.BETTER_AUTH_URL ?? env.NEXT_PUBLIC_APP_URL,

  // Updated: Using new Better Auth 1.3+ hooks format with createAuthMiddleware
  // Transaction-protected: All initialization operations are atomic
  // Auto-rollback: Transaction automatically rolls back on any error
  hooks: {
    after: createAuthMiddleware(async (ctx) => {
      // Only handle sign-up requests
      if (ctx.path.startsWith('/sign-up')) {
        const newSession = ctx.context.newSession;

        // Ensure this is a new user registration (not OAuth callback)
        if (newSession?.user) {
          const registereduser = newSession.user;

          try {
            logger.info(
              { userId: registereduser.id, email: registereduser.email },
              'user registered, starting initialization'
            );

            const registrationSource = detectRegistrationSource(ctx.path);
            await ensureUserInitialized({
              userId: registereduser.id,
              email: registereduser.email,
              source: registrationSource,
            });

            logger.info(
              { userId: registereduser.id },
              'user initialization completed successfully'
            );
          } catch (error) {
            // - Transaction will automatically rollback

            logger.error(
              {
                error: error,
                userId: registereduser.id,
                email: registereduser.email,
              },
              'user initialization failed - transaction will be rolled back automatically'
            );

            // Clean up with retry mechanism
            await cleanupFailedRegistration(registereduser.id, registereduser.email);

            const errorMessage =
              error instanceof Error ? error.message : 'Unknown initialization error';

            throw new Error(
              `Registration failed: ${errorMessage}. Please try again or contact support if the problem persists.`
            );
          }
        }
      }
    }),
  },

  // Configuration

  advanced: {
    useSecureCookies: shouldUseSecureCookies(),

    // cookie: x.session_token, x.csrf_token, x.oauth_state
    cookiePrefix: 'x',

    crossSubDomainCookies: {
      enabled: false, // IfUsesubdomain needs to be enabled
      domain: undefined,
    },
  },
});

/**
 */
export type Auth = typeof auth;
