/**
 * This file is auto-generated by scripts/generate-module-map.mjs.
 * Do not edit manually.
 *
 * Module count: 4
 */
import type {
  ModuleMapArtifact,
  ModuleRuntimeMapEntry,
} from './module-runtime/loader/module-map-types';

export const MODULE_MAP: Record<string, ModuleRuntimeMapEntry> = {
  "executor-extension-smoke": {
    rootDir: "modules/executor-extension-smoke",
    release: {"generatedAt":"1970-01-01T00:00:00.000Z","buildId":"local-dev","sourceHash":"7f420a1a2b48a1bc59288f924014b4be5b54ce200c841af8066e135c724a0f6e","contractDigest":"76717e7019b32b7a31e51a50804b369b26f104047c5bc92c97357c2e11a7cfd5","sourceFiles":["admin/executor-health.read.ts","capabilities/executor.ts","module.ts"],"capabilitySummary":{"routes":0,"dataModels":0,"permissions":1,"backgroundHandlers":0,"providerRequirements":0,"commercialRequirements":0,"presentationContributions":0}},
    module: () => import("../../modules/executor-extension-smoke/module"),
    admin: {
      "admin/executor-health.read": () => import("../../modules/executor-extension-smoke/admin/executor-health.read")
    },
    capabilities: {
      "executor": () => import("../../modules/executor-extension-smoke/capabilities/executor")
    },
  },
  "platform-smoke": {
    rootDir: "modules/platform-smoke",
    release: {"generatedAt":"1970-01-01T00:00:00.000Z","buildId":"local-dev","sourceHash":"7a12efc8a9de490c58a0b92d62e4e59a2c1341d1b0a12ecc30b483af6f109a59","contractDigest":"b7352977f353d99ba52b61a038545ab11ed1f223a3e092be23fd65de6a91470e","sourceFiles":["actions/ping.ts","api/ping.ts","events/reported.ts","jobs/generate-report.ts","lifecycle/install.ts","module.ts","pages/PlatformSmokePage.tsx","surfaces/PlatformSmokeWidget.tsx","webhooks/ingest.ts","webhooks/workflow-ingest.ts"],"capabilitySummary":{"routes":2,"dataModels":0,"permissions":10,"backgroundHandlers":4,"providerRequirements":0,"commercialRequirements":0,"presentationContributions":2}},
    module: () => import("../../modules/platform-smoke/module"),
    pages: {
      "pages/PlatformSmokePage": () => import("../../modules/platform-smoke/pages/PlatformSmokePage")
    },
    apis: {
      "api/ping": () => import("../../modules/platform-smoke/api/ping")
    },
    actions: {
      "actions/ping": () => import("../../modules/platform-smoke/actions/ping")
    },
    surfaces: {
      "surfaces/PlatformSmokeWidget": () => import("../../modules/platform-smoke/surfaces/PlatformSmokeWidget")
    },
    lifecycle: {
      "lifecycle/install": () => import("../../modules/platform-smoke/lifecycle/install")
    },
    jobs: {
      "jobs/generate-report": () => import("../../modules/platform-smoke/jobs/generate-report")
    },
    events: {
      "events/reported": () => import("../../modules/platform-smoke/events/reported")
    },
    webhooks: {
      "webhooks/ingest": () => import("../../modules/platform-smoke/webhooks/ingest"),
      "webhooks/workflow-ingest": () => import("../../modules/platform-smoke/webhooks/workflow-ingest")
    },
  },
  "public-tool-smoke": {
    rootDir: "modules/public-tool-smoke",
    release: {"generatedAt":"1970-01-01T00:00:00.000Z","buildId":"local-dev","sourceHash":"597c5166e297730e7a42944cbf30165cda33a088d02b931b4f668fa9a97e45a5","contractDigest":"5685a7ccdbefa0f074ec627211869c33cfde757e34ad96f64bb8ed591f2eaf7a","sourceFiles":["actions/format-sample.ts","api/format-json.ts","loaders/public-tool-metadata.ts","module.ts","pages/PublicToolPage.tsx"],"capabilitySummary":{"routes":2,"dataModels":0,"permissions":2,"backgroundHandlers":0,"providerRequirements":0,"commercialRequirements":1,"presentationContributions":1}},
    module: () => import("../../modules/public-tool-smoke/module"),
    pages: {
      "pages/PublicToolPage": () => import("../../modules/public-tool-smoke/pages/PublicToolPage")
    },
    apis: {
      "api/format-json": () => import("../../modules/public-tool-smoke/api/format-json")
    },
    loaders: {
      "loaders/public-tool-metadata": () => import("../../modules/public-tool-smoke/loaders/public-tool-metadata")
    },
    actions: {
      "actions/format-sample": () => import("../../modules/public-tool-smoke/actions/format-sample")
    },
  },
  "resource-smoke": {
    rootDir: "modules/resource-smoke",
    release: {"generatedAt":"1970-01-01T00:00:00.000Z","buildId":"local-dev","sourceHash":"c1ec2897cc65bfa169b4c5ed4174274f2b61a613b6fc256c8b5b0cd1311e934b","contractDigest":"57a761066fbbbc2c02da1d31233ef89ea909638f9c55090eae89740ec1851143","sourceFiles":[".ploykit/generated/data-plan.json",".ploykit/generated/data-types.ts",".ploykit/generated/openapi.json","actions/create-note.ts","api/notes.ts","migrations/0001_generated.sql","module.ts","pages/NoteCreatePage.tsx","pages/NoteDetailPage.tsx","pages/NoteEditPage.tsx","pages/NotesListPage.tsx"],"capabilitySummary":{"routes":5,"dataModels":5,"permissions":4,"backgroundHandlers":0,"providerRequirements":0,"commercialRequirements":0,"presentationContributions":1}},
    module: () => import("../../modules/resource-smoke/module"),
    pages: {
      "pages/NoteCreatePage": () => import("../../modules/resource-smoke/pages/NoteCreatePage"),
      "pages/NoteDetailPage": () => import("../../modules/resource-smoke/pages/NoteDetailPage"),
      "pages/NoteEditPage": () => import("../../modules/resource-smoke/pages/NoteEditPage"),
      "pages/NotesListPage": () => import("../../modules/resource-smoke/pages/NotesListPage")
    },
    apis: {
      "api/notes": () => import("../../modules/resource-smoke/api/notes")
    },
    actions: {
      "actions/create-note": () => import("../../modules/resource-smoke/actions/create-note")
    },
  }
};

export const MODULE_MAP_ARTIFACT: ModuleMapArtifact = {
  kind: 'source',
  buildId: "local-dev",
  generatedAt: "1970-01-01T00:00:00.000Z",
  modules: MODULE_MAP,
};
