import { defineModule, Permission } from '@ploykit/module-sdk';

export default defineModule({
  id: 'white-label-site-demo',
  name: 'White Label Site Demo',
  contractVersion: 1,
  version: '0.1.0',
  description: 'White-label public, auth and workspace surfaces for product composition demos.',
  permissions: [
    Permission.SurfaceOverride,
    Permission.SurfaceContribute,
    Permission.NavigationExtend,
    Permission.ThemeWrite,
  ],
  resources: {
    locales: {
      zh: './locales/zh.json',
      en: './locales/en.json',
    },
  },
  i18n: {
    defaultLanguage: 'zh',
    requiredLanguages: ['zh', 'en'],
    namespaces: ['nav', 'pages', 'seo', 'forms'],
    strict: true,
  },
  presentation: {
    whiteLabel: true,
    replaces: [
      'host.page:site.home',
      'host.page:site.pricing',
      'host.page:site.about',
      'host.page:site.contact',
      'host.page:site.docs',
      'host.page:site.privacy',
      'host.page:site.terms',
      'host.page:auth.login',
      'host.page:auth.register',
      'host.page:auth.forgotPassword',
      'host.page:auth.resetPassword',
      'host.page:dashboard.home',
    ],
    seoNamespaces: ['seo'],
    themeScope: 'site',
  },
  theme: {
    tokens: {
      colorPrimary: '#2563eb',
      colorSuccess: '#059669',
      colorWarning: '#d97706',
      radiusControl: '10px',
      radiusPanel: '18px',
    },
  },
  navigation: [
    {
      location: 'site.header',
      labelKey: 'nav.dashboard',
      fallbackLabel: 'Workspace',
      path: '/dashboard',
      weight: 50,
    },
    {
      location: 'site.footer',
      labelKey: 'nav.support',
      fallbackLabel: 'Support',
      path: '/contact',
      weight: 10,
    },
  ],
  surfaces: {
    'host.page:site.home': {
      mode: 'replace',
      component: './surfaces/HomePage',
      loader: './loaders/home-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:site.pricing': {
      mode: 'replace',
      component: './surfaces/PricingPage',
      loader: './loaders/pricing-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:site.about': {
      mode: 'replace',
      component: './surfaces/AboutPage',
      loader: './loaders/about-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:site.contact': {
      mode: 'replace',
      component: './surfaces/ContactPage',
      loader: './loaders/contact-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:site.docs': {
      mode: 'replace',
      component: './surfaces/DocsPage',
      loader: './loaders/docs-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:site.privacy': {
      mode: 'replace',
      component: './surfaces/PrivacyPage',
      loader: './loaders/privacy-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:site.terms': {
      mode: 'replace',
      component: './surfaces/TermsPage',
      loader: './loaders/terms-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:auth.login': {
      mode: 'replace',
      component: './surfaces/LoginPage',
      loader: './loaders/auth-login-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:auth.register': {
      mode: 'replace',
      component: './surfaces/RegisterPage',
      loader: './loaders/auth-register-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:auth.forgotPassword': {
      mode: 'replace',
      component: './surfaces/ForgotPasswordPage',
      loader: './loaders/auth-forgot-password-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:auth.resetPassword': {
      mode: 'replace',
      component: './surfaces/ResetPasswordPage',
      loader: './loaders/auth-reset-password-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:dashboard.home': {
      mode: 'replace',
      component: './surfaces/DashboardHomePage',
      loader: './loaders/dashboard-home-meta',
      permissions: [Permission.SurfaceOverride],
      priority: 100,
    },
    'host.page:admin.modules:header.actions': {
      mode: 'action',
      component: './surfaces/AdminModulesActions',
      permissions: [Permission.SurfaceContribute],
      priority: 20,
    },
    'host.page:site.home:hero': {
      mode: 'prepend',
      component: './surfaces/HomeHero',
      permissions: [Permission.SurfaceContribute],
      priority: 10,
    },
  },
});
