import { definePlugin, Permission } from '@ploykit/plugin-sdk';

export default definePlugin({
  id: 'capability-demo',
  name: 'Capability Demo',
  version: '0.1.0',
  description: 'End-to-end demo plugin for the host platform capability surface.',
  kind: 'tool',
  trustLevel: 'trusted',
  permissions: [
    Permission.StorageRead,
    Permission.StorageWrite,
    Permission.ArtifactsRead,
    Permission.ArtifactsWrite,
    Permission.FilesRead,
    Permission.FilesWrite,
    Permission.WorkspaceRead,
    Permission.WorkspaceWrite,
    Permission.RagRead,
    Permission.RagWrite,
    Permission.RunsRead,
    Permission.RunsWrite,
    Permission.ConnectorsRead,
    Permission.ConnectorsInvoke,
    Permission.ConnectorsManage,
    Permission.ApiKeysRead,
    Permission.ApiKeysWrite,
    Permission.RateLimitCheck,
    Permission.AiGenerate,
    Permission.AiEmbed,
    Permission.ConfigRead,
    Permission.ConfigWrite,
    Permission.SecretsRead,
    Permission.SecretsWrite,
    Permission.CreditsRead,
    Permission.CreditsConsume,
    Permission.BillingRead,
    Permission.BillingWrite,
    Permission.AuditWrite,
    Permission.UsageWrite,
    Permission.MeteringWrite,
    Permission.EventsEmit,
    Permission.EventsSubscribe,
    Permission.JobsEnqueue,
    Permission.JobsRegister,
    Permission.WebhookReceive,
    Permission.NotificationsSend,
    Permission.UiToast,
    Permission.NavigationExtend,
    Permission.ExternalHttp,
  ],
  egress: ['https://example.com'],
  data: {
    collections: {
      capability_demo_items: {
        fields: {
          title: { type: 'string', required: true, maxLength: 120 },
          status: { type: 'string', required: true, enum: ['open', 'done', 'archived'] },
          sequence: { type: 'integer', required: true, default: 0 },
          metadata: { type: 'json?', default: {} },
        },
        indexes: [{ fields: ['status'] }, { fields: ['sequence'] }],
      },
    },
  },
  config: {
    defaults: {
      mode: 'demo',
      selfTestEnabled: true,
    },
  },
  resources: {
    assets: [
      {
        path: './assets/editor.worker.js',
        kind: 'worker',
        contentType: 'application/javascript; charset=utf-8',
        maxBytes: 4096,
      },
      {
        path: './assets/template.svg',
        kind: 'asset',
        contentType: 'image/svg+xml; charset=utf-8',
        maxBytes: 4096,
      },
    ],
  },
  theme: {
    tokens: {
      common: {
        colorPrimary: '#0369a1',
      },
      header: {
        borderBottom: '1px solid #bae6fd',
      },
    },
  },
  meters: [
    {
      id: 'capability-demo.ocr.page',
      unit: 'page',
      defaultCreditCost: 1,
      billable: true,
      description: 'Simulated OCR page processing.',
    },
    {
      id: 'capability-demo.image.item',
      unit: 'item',
      defaultCreditCost: 2,
      billable: true,
      description: 'Simulated image cutout operation.',
    },
    {
      id: 'capability-demo.csv.request',
      unit: 'request',
      defaultCreditCost: 1,
      billable: true,
      description: 'CSV conversion API request.',
    },
    {
      id: 'capability-demo.ai.generate',
      unit: 'request',
      defaultCreditCost: 1,
      billable: true,
      description: 'Host AI text generation request.',
    },
    {
      id: 'capability-demo.ai.embed',
      unit: 'request',
      defaultCreditCost: 1,
      billable: true,
      description: 'Host AI embedding request.',
    },
    {
      id: 'capability-demo.external-api',
      unit: 'request',
      defaultCreditCost: 1,
      billable: true,
      description: 'External API credit probe.',
    },
    {
      id: 'capability-demo.connector.demo-service',
      unit: 'request',
      defaultCreditCost: 1,
      billable: true,
      description: 'Connector call credit probe.',
    },
    {
      id: 'capability-demo.selftest.request',
      unit: 'request',
      defaultCreditCost: 0,
      billable: false,
      description: 'Non-billable host capability self-test request.',
    },
  ],
  routes: {
    tools: [
      {
        path: '/json-format',
        component: './pages/JsonFormatTool',
        auth: 'public',
        seo: {
          title: 'JSON Formatter',
          description: 'Format, inspect, and copy JSON in the Capability Demo tool.',
          canonical: '/tools/json-format',
          robots: { index: true, follow: true },
          openGraph: { image: '/opengraph-image' },
          structuredData: {
            '@context': 'https://schema.org',
            '@type': 'SoftwareApplication',
            name: 'JSON Formatter',
            applicationCategory: 'DeveloperApplication',
          },
        },
        sitemap: { include: true, changeFrequency: 'weekly', priority: 0.7 },
        publicAliases: [
          {
            path: '/json',
            seo: {
              title: 'JSON Formatter',
              description: 'Format, inspect, and copy JSON from a plugin-owned public alias.',
              canonical: '/json',
              robots: { index: true, follow: true },
              openGraph: { image: '/opengraph-image' },
              structuredData: {
                '@context': 'https://schema.org',
                '@type': 'SoftwareApplication',
                name: 'Plugin Public Alias JSON Formatter',
                applicationCategory: 'DeveloperApplication',
              },
            },
            sitemap: { include: true, changeFrequency: 'weekly', priority: 0.7 },
          },
        ],
        cache: { strategy: 'public', maxAgeSeconds: 300, staleWhileRevalidateSeconds: 600 },
        anonymousPolicy: {
          rateLimit: { bucket: ['ip', 'route'], limit: 60, window: '1m' },
          captcha: 'never',
          allowHighCostActions: false,
        },
      },
      {
        path: '/pdf-ocr',
        component: './pages/PdfOcrTool',
        auth: 'public',
        seo: {
          title: 'PDF OCR Demo',
          description: 'Preview the host files and metering flow for PDF OCR tools.',
          canonical: '/tools/pdf-ocr',
          robots: { index: true, follow: true },
        },
        sitemap: { include: true, changeFrequency: 'weekly', priority: 0.6 },
        cache: { strategy: 'public', maxAgeSeconds: 300 },
        anonymousPolicy: {
          rateLimit: { bucket: ['ip', 'route'], limit: 20, window: '1m' },
          maxUploadBytes: 5 * 1024 * 1024,
          captcha: 'auto',
          allowHighCostActions: false,
        },
      },
      {
        path: '/image-cutout',
        component: './pages/ImageCutoutTool',
        auth: 'public',
        seo: {
          title: 'Image Cutout Demo',
          description: 'Preview the host image file and metering flow for background cutouts.',
          canonical: '/tools/image-cutout',
          robots: { index: true, follow: true },
        },
        sitemap: { include: true, changeFrequency: 'weekly', priority: 0.6 },
        cache: { strategy: 'public', maxAgeSeconds: 300 },
        anonymousPolicy: {
          rateLimit: { bucket: ['ip', 'route'], limit: 20, window: '1m' },
          maxUploadBytes: 5 * 1024 * 1024,
          captcha: 'auto',
          allowHighCostActions: false,
        },
      },
      {
        path: '/dev-assets',
        component: './pages/DevAssetsTool',
        auth: 'public',
        seo: {
          title: 'Plugin Assets Demo',
          description: 'Validate plugin-declared static asset serving.',
          canonical: '/tools/dev-assets',
          robots: { index: false, follow: true },
        },
        sitemap: { include: false },
        cache: { strategy: 'public', maxAgeSeconds: 300 },
        anonymousPolicy: {
          rateLimit: { bucket: ['ip', 'route'], limit: 30, window: '1m' },
          captcha: 'never',
          allowHighCostActions: false,
        },
      },
      {
        path: '/self-test',
        component: './pages/SelfTestTool',
        auth: 'auth',
        seo: {
          title: 'Capability Self Test',
          description: 'Run the capability demo plugin against real host platform APIs.',
          canonical: '/tools/self-test',
          robots: { index: false, follow: false },
        },
        sitemap: { include: false },
        cache: { strategy: 'private', maxAgeSeconds: 0 },
      },
    ],
    apis: [
      {
        path: '/run',
        handler: './api/run',
        auth: 'auth',
        methods: ['POST'],
      },
      {
        path: '/seo-check',
        handler: './api/seo-check',
        auth: 'public',
        methods: ['POST'],
        anonymousPolicy: {
          rateLimit: { bucket: ['ip', 'route'], limit: 10, window: '1m' },
          captcha: 'always',
          allowHighCostActions: false,
        },
      },
      {
        path: '/self-test',
        handler: './api/self-test',
        auth: 'auth',
        methods: ['POST'],
      },
      {
        path: '/api-key-echo',
        handler: './api/api-key-echo',
        auth: 'auth',
        machineAuth: 'apiKey',
        methods: ['POST'],
        permissions: [Permission.RateLimitCheck, Permission.MeteringWrite],
      },
      {
        path: '/csv-convert',
        handler: './api/csv-convert',
        auth: 'auth',
        machineAuth: 'apiKey',
        methods: ['POST'],
      },
    ],
  },
  events: {
    publishes: ['capability-demo.selftest.event'],
    subscribes: {
      'capability-demo.selftest.event': './events/selftest',
    },
  },
  jobs: {
    'capability-demo.selftest.job': {
      handler: './jobs/selftest',
      timeoutMs: 10000,
      retries: 0,
    },
  },
  webhooks: {
    selfTest: {
      path: '/self-test',
      handler: './webhooks/self-test',
      methods: ['POST'],
      signature: 'none',
    },
  },
  menu: [
    {
      location: 'site.header',
      label: 'JSON',
      path: '/json',
      weight: 60,
    },
    {
      location: 'site.account',
      label: 'Capability Self Test',
      path: '/tools/self-test',
      weight: 80,
    },
  ],
  slots: {
    'route:/json:main.before': {
      component: './slots/JsonAliasBanner',
      priority: 10,
    },
  },
});
