import type { ModuleFileStorageHead } from '@/lib/module-capabilities/files/storage-adapter';
import type { ModuleHostSession } from '@/lib/module-runtime/host/session';
import type {
  RuntimeStoreAuditRecord,
  RuntimeStoreFileRecord,
} from '@/lib/module-runtime/stores/runtime-store-types';
import { assertAdminSession } from './admin-session';
import { getHostRuntime } from './create-host';
import { DEFAULT_HOST_PRODUCT_ID } from './default-scope';
import {
  getHostFileRuntime,
  getHostFileStorage,
  getHostFileStorageStatus,
  type HostFileStorageStatus,
} from './files';

const DEMO_PRODUCT_ID = DEFAULT_HOST_PRODUCT_ID;

export interface AdminFilesView {
  files: RuntimeStoreFileRecord[];
  storage: HostFileStorageStatus;
  reconcile: AdminFileStorageReconcileReport;
}

export interface AdminFileDetailView {
  file: RuntimeStoreFileRecord | null;
  audit: RuntimeStoreAuditRecord[];
  storage: HostFileStorageStatus;
  storageObject: AdminFileStorageObjectView | null;
  access: AdminFileAccessView | null;
  cleanup: AdminFileCleanupView | null;
}

export interface AdminFileStorageObjectView {
  status: 'present' | 'missing' | 'error';
  key: string;
  checkedAt: string;
  sizeBytes: number | null;
  checksum: string | null;
  contentType: string | null;
  metadata: Record<string, string>;
  error?: string;
}

export interface AdminFileAccessView {
  openUrl: string | null;
  downloadUrl: string | null;
  mediaGateway: 'public' | 'signed' | 'blocked';
  reason: string;
}

export interface AdminFileCleanupView {
  eligible: boolean;
  physicalObjectPresent: boolean | null;
  latestCleanupAt: string | null;
  command: string;
  reason: string;
}

export type AdminFileStorageReconcileIssue =
  | 'none'
  | 'missing-object'
  | 'deleted-object-present'
  | 'size-mismatch'
  | 'checksum-mismatch'
  | 'storage-error';

export interface AdminFileStorageReconcileItem {
  fileId: string;
  name: string;
  moduleId: string;
  status: RuntimeStoreFileRecord['status'];
  storageKey: string;
  issue: AdminFileStorageReconcileIssue;
  objectStatus: AdminFileStorageObjectView['status'];
  metadataSizeBytes: number;
  objectSizeBytes: number | null;
  metadataChecksum: string | null;
  objectChecksum: string | null;
  cleanupCandidate: boolean;
  error?: string;
}

export interface AdminFileStorageOrphanObject {
  key: string;
  sizeBytes: number;
  checksum: string;
  contentType: string | null;
  metadata: Record<string, string>;
}

export interface AdminFileStorageReconcileReport {
  checkedAt: string;
  totalFiles: number;
  checkedFiles: number;
  limit: number;
  orphanScanSupported: boolean;
  issues: number;
  presentObjects: number;
  missingObjects: number;
  orphanObjects: number;
  deletedObjectsPresent: number;
  missingActiveObjects: number;
  sizeMismatches: number;
  checksumMismatches: number;
  metadataBytes: number;
  physicalBytes: number;
  orphanBytes: number;
  command: string;
  items: AdminFileStorageReconcileItem[];
  orphans: AdminFileStorageOrphanObject[];
}

function uniqueById<TRecord extends { id: string }>(records: readonly TRecord[]): TRecord[] {
  return Array.from(new Map(records.map((record) => [record.id, record])).values());
}

function buildAdminFileAccess(file: RuntimeStoreFileRecord): AdminFileAccessView {
  if (file.status !== 'ready' && file.status !== 'published') {
    return {
      openUrl: null,
      downloadUrl: null,
      mediaGateway: 'blocked',
      reason: `File status ${file.status} is not readable through media gateway.`,
    };
  }
  return {
    openUrl: `/api/media/${file.id}`,
    downloadUrl: `/api/media/${file.id}?download=1`,
    mediaGateway: file.status === 'published' || file.visibility === 'public' ? 'public' : 'signed',
    reason:
      file.status === 'published' || file.visibility === 'public'
        ? 'Public file still resolves through host media gateway; storage key is not exposed.'
        : 'Private file requires a signed media gateway token generated by the host.',
  };
}

function fileObjectView(
  file: RuntimeStoreFileRecord,
  head: ModuleFileStorageHead | null,
  checkedAt: string
): AdminFileStorageObjectView {
  if (!head) {
    return {
      status: 'missing',
      key: file.storageKey,
      checkedAt,
      sizeBytes: null,
      checksum: null,
      contentType: null,
      metadata: {},
    };
  }
  return {
    status: 'present',
    key: file.storageKey,
    checkedAt,
    sizeBytes: head.sizeBytes,
    checksum: head.checksum,
    contentType: head.contentType ?? null,
    metadata: head.metadata,
  };
}

async function inspectAdminFileStorageObject(
  file: RuntimeStoreFileRecord
): Promise<AdminFileStorageObjectView> {
  const checkedAt = new Date().toISOString();
  try {
    const storage = await getHostFileStorage();
    return fileObjectView(file, await storage.storage.head(file.storageKey), checkedAt);
  } catch (error) {
    return {
      status: 'error',
      key: file.storageKey,
      checkedAt,
      sizeBytes: null,
      checksum: null,
      contentType: null,
      metadata: {},
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

function buildAdminFileCleanup(input: {
  file: RuntimeStoreFileRecord;
  storageObject: AdminFileStorageObjectView;
  cleanupAudit: readonly RuntimeStoreAuditRecord[];
}): AdminFileCleanupView {
  const latestCleanupAt =
    [...input.cleanupAudit].sort((left, right) => right.createdAt.localeCompare(left.createdAt))[0]
      ?.createdAt ?? null;
  const physicalObjectPresent =
    input.storageObject.status === 'error' ? null : input.storageObject.status === 'present';
  const eligible = input.file.status === 'deleted';
  return {
    eligible,
    physicalObjectPresent,
    latestCleanupAt,
    command: 'npm run host:files-cleanup-smoke',
    reason: eligible
      ? physicalObjectPresent
        ? 'Deleted metadata still has a physical object; cleanup can remove object bytes while keeping audit metadata.'
        : 'Deleted metadata has no physical object; cleanup is already reflected in storage.'
      : 'Only files marked deleted are eligible for physical object cleanup.',
  };
}

function fileExpectsStorageObject(file: RuntimeStoreFileRecord): boolean {
  return ['ready', 'published', 'archived', 'quarantined'].includes(file.status);
}

function reconcileFileIssue(
  file: RuntimeStoreFileRecord,
  storageObject: AdminFileStorageObjectView
): AdminFileStorageReconcileIssue {
  if (storageObject.status === 'error') {
    return 'storage-error';
  }
  if (file.status === 'deleted' && storageObject.status === 'present') {
    return 'deleted-object-present';
  }
  if (fileExpectsStorageObject(file) && storageObject.status === 'missing') {
    return 'missing-object';
  }
  if (
    storageObject.status === 'present' &&
    file.sizeBytes > 0 &&
    storageObject.sizeBytes !== null &&
    storageObject.sizeBytes !== file.sizeBytes
  ) {
    return 'size-mismatch';
  }
  if (
    storageObject.status === 'present' &&
    Boolean(file.checksum) &&
    Boolean(storageObject.checksum) &&
    storageObject.checksum !== file.checksum
  ) {
    return 'checksum-mismatch';
  }
  return 'none';
}

function reconcileItem(
  file: RuntimeStoreFileRecord,
  storageObject: AdminFileStorageObjectView
): AdminFileStorageReconcileItem {
  const issue = reconcileFileIssue(file, storageObject);
  return {
    fileId: file.id,
    name: file.name,
    moduleId: file.moduleId,
    status: file.status,
    storageKey: file.storageKey,
    issue,
    objectStatus: storageObject.status,
    metadataSizeBytes: file.sizeBytes,
    objectSizeBytes: storageObject.sizeBytes,
    metadataChecksum: file.checksum ?? null,
    objectChecksum: storageObject.checksum,
    cleanupCandidate: issue === 'deleted-object-present',
    error: storageObject.error,
  };
}

function auditRecordReferencesFile(record: RuntimeStoreAuditRecord, fileId: string): boolean {
  if (record.metadata.fileId === fileId) {
    return true;
  }
  return Array.isArray(record.metadata.fileIds) && record.metadata.fileIds.includes(fileId);
}

export async function getAdminFilesView(): Promise<AdminFilesView> {
  const hostRuntime = await getHostRuntime();
  const [files, storage, reconcile] = await Promise.all([
    hostRuntime.runtimeStore.store.listFiles({
      productId: DEMO_PRODUCT_ID,
      includeDeleted: true,
    }),
    getHostFileStorageStatus(),
    reconcileAdminFileStorage({ productId: DEMO_PRODUCT_ID, limit: 200 }),
  ]);

  return { files, storage, reconcile };
}

export async function reconcileAdminFileStorage(
  input: {
    productId?: string;
    limit?: number;
    orphanLimit?: number;
  } = {}
): Promise<AdminFileStorageReconcileReport> {
  const productId = input.productId ?? DEMO_PRODUCT_ID;
  const limit = input.limit ?? 500;
  const orphanLimit = input.orphanLimit ?? limit;
  const checkedAt = new Date().toISOString();
  const hostRuntime = await getHostRuntime();
  const storage = await getHostFileStorage();
  const files = await hostRuntime.runtimeStore.store.listFiles({
    productId,
    includeDeleted: true,
  });
  const checkedFiles = files.slice(0, limit);
  const items: AdminFileStorageReconcileItem[] = [];
  for (const file of checkedFiles) {
    items.push(reconcileItem(file, await inspectAdminFileStorageObject(file)));
  }

  const issueItems = items.filter((item) => item.issue !== 'none');
  const presentItems = items.filter((item) => item.objectStatus === 'present');
  const metadataKeys = new Set(files.map((file) => file.storageKey));
  const listedObjects = storage.storage.list
    ? await storage.storage.list({ prefix: `${productId}/`, limit: orphanLimit })
    : [];
  const orphans: AdminFileStorageOrphanObject[] = listedObjects
    .filter((object) => !metadataKeys.has(object.key))
    .slice(0, 50)
    .map((object) => ({
      key: object.key,
      sizeBytes: object.sizeBytes,
      checksum: object.checksum,
      contentType: object.contentType ?? null,
      metadata: object.metadata,
    }));
  return {
    checkedAt,
    totalFiles: files.length,
    checkedFiles: checkedFiles.length,
    limit,
    orphanScanSupported: Boolean(storage.storage.list),
    issues: issueItems.length + orphans.length,
    presentObjects: presentItems.length,
    missingObjects: items.filter((item) => item.objectStatus === 'missing').length,
    orphanObjects: orphans.length,
    deletedObjectsPresent: items.filter((item) => item.issue === 'deleted-object-present').length,
    missingActiveObjects: items.filter((item) => item.issue === 'missing-object').length,
    sizeMismatches: items.filter((item) => item.issue === 'size-mismatch').length,
    checksumMismatches: items.filter((item) => item.issue === 'checksum-mismatch').length,
    metadataBytes: items.reduce((total, item) => total + item.metadataSizeBytes, 0),
    physicalBytes:
      listedObjects.length > 0
        ? listedObjects.reduce((total, item) => total + item.sizeBytes, 0)
        : presentItems.reduce((total, item) => total + (item.objectSizeBytes ?? 0), 0),
    orphanBytes: orphans.reduce((total, item) => total + item.sizeBytes, 0),
    command: 'npm run host:files-reconcile-smoke',
    items: issueItems.slice(0, 50),
    orphans,
  };
}

export async function getAdminFileDetailView(fileId: string): Promise<AdminFileDetailView> {
  const hostRuntime = await getHostRuntime();
  const file = await hostRuntime.runtimeStore.store.getFile(fileId);
  if (!file) {
    return {
      file: null,
      storage: await getHostFileStorageStatus(),
      audit: [],
      storageObject: null,
      access: null,
      cleanup: null,
    };
  }

  const [audit, cleanupAudit, storage, storageObject] = await Promise.all([
    hostRuntime.runtimeStore.store.listAudit({
      productId: file.productId,
      moduleId: file.moduleId,
    }),
    hostRuntime.runtimeStore.store.listAudit({
      productId: file.productId,
      type: 'admin.file.cleanup_deleted',
    }),
    getHostFileStorageStatus(),
    inspectAdminFileStorageObject(file),
  ]);
  return {
    file,
    storage,
    storageObject,
    access: buildAdminFileAccess(file),
    cleanup: buildAdminFileCleanup({ file, storageObject, cleanupAudit }),
    audit: uniqueById([...audit, ...cleanupAudit])
      .filter((record) => auditRecordReferencesFile(record, fileId))
      .slice(0, 50),
  };
}

export async function quarantineAdminFile(
  session: ModuleHostSession,
  fileId: string,
  reason = 'Admin quarantine'
) {
  assertAdminSession(session);
  const hostRuntime = await getHostRuntime();
  const file = await hostRuntime.runtimeStore.store.updateFile(fileId, {
    status: 'quarantined',
    quarantinedAt: new Date().toISOString(),
    metadata: { quarantineReason: reason },
  });
  await hostRuntime.runtimeStore.store.recordAudit({
    productId: file.productId,
    workspaceId: file.workspaceId,
    moduleId: file.moduleId,
    actorId: session.actorId ?? session.user?.id,
    type: 'admin.file.quarantined',
    metadata: { fileId, reason },
  });
  return file;
}

export async function restoreAdminFile(session: ModuleHostSession, fileId: string) {
  assertAdminSession(session);
  const hostRuntime = await getHostRuntime();
  const file = await hostRuntime.runtimeStore.store.updateFile(fileId, {
    status: 'ready',
  });
  await hostRuntime.runtimeStore.store.recordAudit({
    productId: file.productId,
    workspaceId: file.workspaceId,
    moduleId: file.moduleId,
    actorId: session.actorId ?? session.user?.id,
    type: 'admin.file.restored',
    metadata: { fileId },
  });
  return file;
}

export async function archiveAdminFile(session: ModuleHostSession, fileId: string) {
  assertAdminSession(session);
  const hostRuntime = await getHostRuntime();
  const file = await hostRuntime.runtimeStore.store.updateFile(fileId, {
    status: 'archived',
  });
  await hostRuntime.runtimeStore.store.recordAudit({
    productId: file.productId,
    workspaceId: file.workspaceId,
    moduleId: file.moduleId,
    actorId: session.actorId ?? session.user?.id,
    type: 'admin.file.archived',
    metadata: { fileId },
  });
  return file;
}

export async function deleteAdminFile(session: ModuleHostSession, fileId: string) {
  assertAdminSession(session);
  const hostRuntime = await getHostRuntime();
  const file = await hostRuntime.runtimeStore.store.updateFile(fileId, {
    status: 'deleted',
    deletedAt: new Date().toISOString(),
  });
  await hostRuntime.runtimeStore.store.recordAudit({
    productId: file.productId,
    workspaceId: file.workspaceId,
    moduleId: file.moduleId,
    actorId: session.actorId ?? session.user?.id,
    type: 'admin.file.deleted',
    metadata: { fileId },
  });
  return file;
}

export async function cleanupAdminDeletedFiles(session: ModuleHostSession) {
  assertAdminSession(session);
  const files = await getHostFileRuntime(session);
  const deleted = await files.cleanupDeletedFiles();
  const hostRuntime = await getHostRuntime();
  await hostRuntime.runtimeStore.store.recordAudit({
    productId: session.productId ?? DEMO_PRODUCT_ID,
    workspaceId: session.workspaceId ?? null,
    actorId: session.actorId ?? session.user?.id,
    type: 'admin.file.cleanup_deleted',
    metadata: {
      deleted: deleted.length,
      fileIds: deleted.slice(0, 100).map((file) => file.id),
      storageKeys: deleted.slice(0, 100).map((file) => file.storageKey),
      truncated: deleted.length > 100,
    },
  });
  return deleted;
}

export async function bulkUpdateAdminFiles(
  session: ModuleHostSession,
  input: {
    fileIds: readonly string[];
    action: 'archive' | 'delete';
    reason?: string;
  }
) {
  assertAdminSession(session);
  const uniqueIds = [...new Set(input.fileIds.map((id) => id.trim()).filter(Boolean))].slice(
    0,
    100
  );
  const results: RuntimeStoreFileRecord[] = [];
  for (const fileId of uniqueIds) {
    if (input.action === 'archive') {
      results.push(await archiveAdminFile(session, fileId));
    } else {
      results.push(await deleteAdminFile(session, fileId));
    }
  }
  const hostRuntime = await getHostRuntime();
  await hostRuntime.runtimeStore.store.recordAudit({
    productId: session.productId ?? DEMO_PRODUCT_ID,
    workspaceId: session.workspaceId ?? null,
    actorId: session.actorId ?? session.user?.id,
    type: `admin.file.bulk_${input.action}`,
    metadata: {
      fileIds: uniqueIds,
      count: results.length,
      reason: input.reason ?? `Admin bulk ${input.action} files`,
    },
  });
  return results;
}
