export default function HomePage() {
  return (
    <main>
      <p className="text-sm font-semibold uppercase text-primary">Product module</p>
      <h1 className="mt-2 text-4xl font-semibold text-foreground">__MODULE_NAME__</h1>
      <p className="mt-3 text-muted-foreground">White-label product page generated by PloyKit.</p>
      <a className="mt-5 inline-flex min-h-10 items-center rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground" href="/dashboard/__MODULE_ID__">Open console</a>
    </main>
  );
}
