export default function HomePage() {
  return {
    eyebrow: 'Product module',
    title: '__MODULE_NAME__',
    description: 'White-label product page generated by PloyKit.',
    primaryAction: {
      label: 'Open console',
      href: '/dashboard/__MODULE_ID__',
    },
  };
}
