export const Permission = {
  DataDocumentRead: 'data.document.read',
  DataDocumentWrite: 'data.document.write',
  DataTableRead: 'data.table.read',
  DataTableWrite: 'data.table.write',
  DataTransaction: 'data.transaction',
  DataSqlRead: 'data.sql.read',
  DataSqlWrite: 'data.sql.write',
  DataSchemaManage: 'data.schema.manage',

  NavigationExtend: 'navigation.extend',
  SurfaceContribute: 'surface.contribute',
  SurfaceOverride: 'surface.override',
  ThemeWrite: 'theme.write',
  HeadWrite: 'head.write',
  ScriptWrite: 'script.write',

  RunsRead: 'runs.read',
  RunsWrite: 'runs.write',
  JobsEnqueue: 'jobs.enqueue',
  JobsRegister: 'jobs.register',
  EventsEmit: 'events.emit',
  EventsSubscribe: 'events.subscribe',
  WebhookReceive: 'webhook.receive',
  CacheAccess: 'cache.access',

  FilesRead: 'files.read',
  FilesWrite: 'files.write',
  FilesPublish: 'files.publish',
  ArtifactsRead: 'artifacts.read',
  ArtifactsWrite: 'artifacts.write',
  ResourceBindingsRead: 'resourceBindings.read',
  ResourceBindingsWrite: 'resourceBindings.write',
  ApiKeysRead: 'apiKeys.read',
  ApiKeysWrite: 'apiKeys.write',
  RateLimitCheck: 'rateLimit.check',

  ExternalHttp: 'http.external',
  ConnectorsRead: 'connectors.read',
  ConnectorsManage: 'connectors.manage',
  ConnectorsInvoke: 'connectors.invoke',
  ServicesInvoke: 'services.invoke',
  SecretsRead: 'secrets.read',
  SecretsWrite: 'secrets.write',
  ConfigRead: 'config.read',
  ConfigWrite: 'config.write',

  AiGenerate: 'ai.generate',
  AiEmbed: 'ai.embed',
  RagRead: 'rag.read',
  RagWrite: 'rag.write',

  UsageWrite: 'usage.write',
  AuditWrite: 'audit.write',
  AdminResourcesRead: 'adminResources.read',
  AdminResourcesWrite: 'adminResources.write',
  SubjectsRead: 'subjects.read',
  MeteringWrite: 'metering.write',
  CreditsRead: 'credits.read',
  CreditsConsume: 'credits.consume',
  CreditsWrite: 'credits.write',
  EntitlementsRead: 'entitlements.read',
  EntitlementsWrite: 'entitlements.write',
  BillingRead: 'billing.read',
  BillingWrite: 'billing.write',
  CommerceRead: 'commerce.read',
  CommerceWrite: 'commerce.write',
  CommerceApply: 'commerce.apply',
  RedeemCodesRead: 'redeemCodes.read',
  RedeemCodesWrite: 'redeemCodes.write',
  RedeemCodesRedeem: 'redeemCodes.redeem',
  RiskRead: 'risk.read',
  RiskWrite: 'risk.write',
  NotificationsRead: 'notifications.read',
  NotificationsSend: 'notifications.send',

  RuntimeManage: 'runtime.manage',
  ProductManage: 'product.manage',
  AuthManage: 'auth.manage',
  UnsafeSqlRaw: 'unsafe.sql.raw',
  UnsafeInternalResource: 'unsafe.internal_resource',
} as const;

export type PermissionValue = (typeof Permission)[keyof typeof Permission];

export type PermissionRiskLevel = 'low' | 'medium' | 'high' | 'critical';
export type PermissionScopeLevel = 'user' | 'workspace' | 'product' | 'system' | 'external';

export interface PermissionRegistryEntry {
  value: PermissionValue;
  group:
    | 'data'
    | 'presentation'
    | 'background'
    | 'files'
    | 'providers'
    | 'ai'
    | 'commerce'
    | 'security'
    | 'system';
  labelKey: string;
  risk: PermissionRiskLevel;
  scope: PermissionScopeLevel;
  ctxCapability?: string;
  runtime?: 'request' | 'system' | 'reserved';
  suggestedTemplate?: 'basic' | 'dashboard' | 'crud' | 'connector' | 'job' | 'white-label';
}

export const SystemOnlyPermissions = new Set<PermissionValue>([
  Permission.DataSchemaManage,
  Permission.RuntimeManage,
  Permission.ProductManage,
  Permission.AuthManage,
  Permission.UnsafeSqlRaw,
  Permission.UnsafeInternalResource,
]);

export const ModulePermissionValues = new Set<PermissionValue>(
  Object.values(Permission) as PermissionValue[]
);

export const ReservedRuntimePermissions = new Set<PermissionValue>([
  Permission.ConfigWrite,
  Permission.SecretsWrite,
  Permission.SubjectsRead,
  Permission.ConnectorsManage,
]);

export const PermissionRegistry: Record<PermissionValue, PermissionRegistryEntry> = {
  [Permission.DataDocumentRead]: {
    value: Permission.DataDocumentRead,
    group: 'data',
    labelKey: 'permissions.data.documentRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.data.document',
    suggestedTemplate: 'crud',
  },
  [Permission.DataDocumentWrite]: {
    value: Permission.DataDocumentWrite,
    group: 'data',
    labelKey: 'permissions.data.documentWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.data.document',
    suggestedTemplate: 'crud',
  },
  [Permission.DataTableRead]: {
    value: Permission.DataTableRead,
    group: 'data',
    labelKey: 'permissions.data.tableRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.data.table',
    suggestedTemplate: 'crud',
  },
  [Permission.DataTableWrite]: {
    value: Permission.DataTableWrite,
    group: 'data',
    labelKey: 'permissions.data.tableWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.data.table',
    suggestedTemplate: 'crud',
  },
  [Permission.DataTransaction]: {
    value: Permission.DataTransaction,
    group: 'data',
    labelKey: 'permissions.data.transaction',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.data.transaction',
    suggestedTemplate: 'crud',
  },
  [Permission.DataSqlRead]: {
    value: Permission.DataSqlRead,
    group: 'data',
    labelKey: 'permissions.data.sqlRead',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.data.sql',
    suggestedTemplate: 'crud',
  },
  [Permission.DataSqlWrite]: {
    value: Permission.DataSqlWrite,
    group: 'data',
    labelKey: 'permissions.data.sqlWrite',
    risk: 'critical',
    scope: 'workspace',
    ctxCapability: 'ctx.data.sql',
    suggestedTemplate: 'crud',
  },
  [Permission.DataSchemaManage]: {
    value: Permission.DataSchemaManage,
    group: 'system',
    labelKey: 'permissions.system.dataSchemaManage',
    risk: 'critical',
    scope: 'system',
  },
  [Permission.NavigationExtend]: {
    value: Permission.NavigationExtend,
    group: 'presentation',
    labelKey: 'permissions.presentation.navigationExtend',
    risk: 'low',
    scope: 'product',
    suggestedTemplate: 'dashboard',
  },
  [Permission.SurfaceContribute]: {
    value: Permission.SurfaceContribute,
    group: 'presentation',
    labelKey: 'permissions.presentation.surfaceContribute',
    risk: 'medium',
    scope: 'product',
    suggestedTemplate: 'dashboard',
  },
  [Permission.SurfaceOverride]: {
    value: Permission.SurfaceOverride,
    group: 'presentation',
    labelKey: 'permissions.presentation.surfaceOverride',
    risk: 'high',
    scope: 'product',
    suggestedTemplate: 'white-label',
  },
  [Permission.ThemeWrite]: {
    value: Permission.ThemeWrite,
    group: 'presentation',
    labelKey: 'permissions.presentation.themeWrite',
    risk: 'high',
    scope: 'product',
    suggestedTemplate: 'white-label',
  },
  [Permission.HeadWrite]: {
    value: Permission.HeadWrite,
    group: 'presentation',
    labelKey: 'permissions.presentation.headWrite',
    risk: 'high',
    scope: 'product',
    suggestedTemplate: 'white-label',
  },
  [Permission.ScriptWrite]: {
    value: Permission.ScriptWrite,
    group: 'presentation',
    labelKey: 'permissions.presentation.scriptWrite',
    risk: 'critical',
    scope: 'product',
    suggestedTemplate: 'white-label',
  },
  [Permission.RunsRead]: {
    value: Permission.RunsRead,
    group: 'background',
    labelKey: 'permissions.background.runsRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.runs',
    suggestedTemplate: 'job',
  },
  [Permission.RunsWrite]: {
    value: Permission.RunsWrite,
    group: 'background',
    labelKey: 'permissions.background.runsWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.runs',
    suggestedTemplate: 'job',
  },
  [Permission.JobsEnqueue]: {
    value: Permission.JobsEnqueue,
    group: 'background',
    labelKey: 'permissions.background.jobsEnqueue',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.jobs',
    suggestedTemplate: 'job',
  },
  [Permission.JobsRegister]: {
    value: Permission.JobsRegister,
    group: 'background',
    labelKey: 'permissions.background.jobsRegister',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.jobs',
    suggestedTemplate: 'job',
  },
  [Permission.EventsEmit]: {
    value: Permission.EventsEmit,
    group: 'background',
    labelKey: 'permissions.background.eventsEmit',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.events',
    suggestedTemplate: 'job',
  },
  [Permission.EventsSubscribe]: {
    value: Permission.EventsSubscribe,
    group: 'background',
    labelKey: 'permissions.background.eventsSubscribe',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.events',
    suggestedTemplate: 'job',
  },
  [Permission.WebhookReceive]: {
    value: Permission.WebhookReceive,
    group: 'background',
    labelKey: 'permissions.background.webhookReceive',
    risk: 'high',
    scope: 'external',
    ctxCapability: 'ctx.webhooks',
    suggestedTemplate: 'connector',
  },
  [Permission.CacheAccess]: {
    value: Permission.CacheAccess,
    group: 'presentation',
    labelKey: 'permissions.presentation.cacheAccess',
    risk: 'medium',
    scope: 'product',
    ctxCapability: 'ctx.cache',
  },
  [Permission.FilesRead]: {
    value: Permission.FilesRead,
    group: 'files',
    labelKey: 'permissions.files.read',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.files',
    suggestedTemplate: 'connector',
  },
  [Permission.FilesWrite]: {
    value: Permission.FilesWrite,
    group: 'files',
    labelKey: 'permissions.files.write',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.files',
    suggestedTemplate: 'connector',
  },
  [Permission.FilesPublish]: {
    value: Permission.FilesPublish,
    group: 'files',
    labelKey: 'permissions.files.publish',
    risk: 'high',
    scope: 'product',
    ctxCapability: 'ctx.files',
    suggestedTemplate: 'connector',
  },
  [Permission.ArtifactsRead]: {
    value: Permission.ArtifactsRead,
    group: 'files',
    labelKey: 'permissions.artifacts.read',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.artifacts',
  },
  [Permission.ArtifactsWrite]: {
    value: Permission.ArtifactsWrite,
    group: 'files',
    labelKey: 'permissions.artifacts.write',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.artifacts',
  },
  [Permission.ResourceBindingsRead]: {
    value: Permission.ResourceBindingsRead,
    group: 'providers',
    labelKey: 'permissions.providers.resourceBindingsRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.resourceBindings',
    suggestedTemplate: 'connector',
  },
  [Permission.ResourceBindingsWrite]: {
    value: Permission.ResourceBindingsWrite,
    group: 'providers',
    labelKey: 'permissions.providers.resourceBindingsWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.resourceBindings',
    suggestedTemplate: 'connector',
  },
  [Permission.ApiKeysRead]: {
    value: Permission.ApiKeysRead,
    group: 'security',
    labelKey: 'permissions.security.apiKeysRead',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.apiKeys',
  },
  [Permission.ApiKeysWrite]: {
    value: Permission.ApiKeysWrite,
    group: 'security',
    labelKey: 'permissions.security.apiKeysWrite',
    risk: 'critical',
    scope: 'workspace',
    ctxCapability: 'ctx.apiKeys',
  },
  [Permission.RateLimitCheck]: {
    value: Permission.RateLimitCheck,
    group: 'security',
    labelKey: 'permissions.security.rateLimitCheck',
    risk: 'medium',
    scope: 'external',
    ctxCapability: 'ctx.rateLimit',
  },
  [Permission.ExternalHttp]: {
    value: Permission.ExternalHttp,
    group: 'providers',
    labelKey: 'permissions.providers.externalHttp',
    risk: 'high',
    scope: 'external',
    ctxCapability: 'ctx.http',
    suggestedTemplate: 'connector',
  },
  [Permission.ConnectorsRead]: {
    value: Permission.ConnectorsRead,
    group: 'providers',
    labelKey: 'permissions.providers.connectorsRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.connectors',
    suggestedTemplate: 'connector',
  },
  [Permission.ConnectorsManage]: {
    value: Permission.ConnectorsManage,
    group: 'providers',
    labelKey: 'permissions.providers.connectorsManage',
    risk: 'high',
    scope: 'workspace',
    runtime: 'reserved',
    suggestedTemplate: 'connector',
  },
  [Permission.ConnectorsInvoke]: {
    value: Permission.ConnectorsInvoke,
    group: 'providers',
    labelKey: 'permissions.providers.connectorsInvoke',
    risk: 'high',
    scope: 'external',
    ctxCapability: 'ctx.connectors',
    suggestedTemplate: 'connector',
  },
  [Permission.ServicesInvoke]: {
    value: Permission.ServicesInvoke,
    group: 'providers',
    labelKey: 'permissions.providers.servicesInvoke',
    risk: 'high',
    scope: 'external',
    ctxCapability: 'ctx.services',
    suggestedTemplate: 'connector',
  },
  [Permission.SecretsRead]: {
    value: Permission.SecretsRead,
    group: 'security',
    labelKey: 'permissions.security.secretsRead',
    risk: 'critical',
    scope: 'workspace',
    ctxCapability: 'ctx.secrets',
  },
  [Permission.SecretsWrite]: {
    value: Permission.SecretsWrite,
    group: 'security',
    labelKey: 'permissions.security.secretsWrite',
    risk: 'critical',
    scope: 'workspace',
    runtime: 'reserved',
  },
  [Permission.ConfigRead]: {
    value: Permission.ConfigRead,
    group: 'providers',
    labelKey: 'permissions.providers.configRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.config',
  },
  [Permission.ConfigWrite]: {
    value: Permission.ConfigWrite,
    group: 'providers',
    labelKey: 'permissions.providers.configWrite',
    risk: 'high',
    scope: 'workspace',
    runtime: 'reserved',
  },
  [Permission.AiGenerate]: {
    value: Permission.AiGenerate,
    group: 'ai',
    labelKey: 'permissions.ai.generate',
    risk: 'high',
    scope: 'external',
    ctxCapability: 'ctx.ai',
    suggestedTemplate: 'connector',
  },
  [Permission.AiEmbed]: {
    value: Permission.AiEmbed,
    group: 'ai',
    labelKey: 'permissions.ai.embed',
    risk: 'high',
    scope: 'external',
    ctxCapability: 'ctx.ai',
    suggestedTemplate: 'connector',
  },
  [Permission.RagRead]: {
    value: Permission.RagRead,
    group: 'ai',
    labelKey: 'permissions.ai.ragRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.rag',
    suggestedTemplate: 'connector',
  },
  [Permission.RagWrite]: {
    value: Permission.RagWrite,
    group: 'ai',
    labelKey: 'permissions.ai.ragWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.rag',
    suggestedTemplate: 'connector',
  },
  [Permission.UsageWrite]: {
    value: Permission.UsageWrite,
    group: 'commerce',
    labelKey: 'permissions.commerce.usageWrite',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.usage',
  },
  [Permission.AuditWrite]: {
    value: Permission.AuditWrite,
    group: 'security',
    labelKey: 'permissions.security.auditWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.audit',
  },
  [Permission.AdminResourcesRead]: {
    value: Permission.AdminResourcesRead,
    group: 'security',
    labelKey: 'permissions.security.adminResourcesRead',
    risk: 'medium',
    scope: 'product',
  },
  [Permission.AdminResourcesWrite]: {
    value: Permission.AdminResourcesWrite,
    group: 'security',
    labelKey: 'permissions.security.adminResourcesWrite',
    risk: 'high',
    scope: 'product',
  },
  [Permission.SubjectsRead]: {
    value: Permission.SubjectsRead,
    group: 'commerce',
    labelKey: 'permissions.commerce.subjectsRead',
    risk: 'medium',
    scope: 'workspace',
    runtime: 'reserved',
  },
  [Permission.MeteringWrite]: {
    value: Permission.MeteringWrite,
    group: 'commerce',
    labelKey: 'permissions.commerce.meteringWrite',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.metering',
  },
  [Permission.CreditsRead]: {
    value: Permission.CreditsRead,
    group: 'commerce',
    labelKey: 'permissions.commerce.creditsRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.credits',
  },
  [Permission.CreditsConsume]: {
    value: Permission.CreditsConsume,
    group: 'commerce',
    labelKey: 'permissions.commerce.creditsConsume',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.credits',
  },
  [Permission.CreditsWrite]: {
    value: Permission.CreditsWrite,
    group: 'commerce',
    labelKey: 'permissions.commerce.creditsWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.credits',
  },
  [Permission.EntitlementsRead]: {
    value: Permission.EntitlementsRead,
    group: 'commerce',
    labelKey: 'permissions.commerce.entitlementsRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.entitlements',
  },
  [Permission.EntitlementsWrite]: {
    value: Permission.EntitlementsWrite,
    group: 'commerce',
    labelKey: 'permissions.commerce.entitlementsWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.entitlements',
  },
  [Permission.BillingRead]: {
    value: Permission.BillingRead,
    group: 'commerce',
    labelKey: 'permissions.commerce.billingRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.billing',
    suggestedTemplate: 'connector',
  },
  [Permission.BillingWrite]: {
    value: Permission.BillingWrite,
    group: 'commerce',
    labelKey: 'permissions.commerce.billingWrite',
    risk: 'critical',
    scope: 'workspace',
    ctxCapability: 'ctx.billing',
    suggestedTemplate: 'connector',
  },
  [Permission.CommerceRead]: {
    value: Permission.CommerceRead,
    group: 'commerce',
    labelKey: 'permissions.commerce.read',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.commerce',
    suggestedTemplate: 'connector',
  },
  [Permission.CommerceWrite]: {
    value: Permission.CommerceWrite,
    group: 'commerce',
    labelKey: 'permissions.commerce.write',
    risk: 'critical',
    scope: 'workspace',
    ctxCapability: 'ctx.commerce',
    suggestedTemplate: 'connector',
  },
  [Permission.CommerceApply]: {
    value: Permission.CommerceApply,
    group: 'commerce',
    labelKey: 'permissions.commerce.apply',
    risk: 'critical',
    scope: 'workspace',
    ctxCapability: 'ctx.commerce',
    suggestedTemplate: 'connector',
  },
  [Permission.RedeemCodesRead]: {
    value: Permission.RedeemCodesRead,
    group: 'commerce',
    labelKey: 'permissions.commerce.redeemCodesRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.redeemCodes',
  },
  [Permission.RedeemCodesWrite]: {
    value: Permission.RedeemCodesWrite,
    group: 'commerce',
    labelKey: 'permissions.commerce.redeemCodesWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.redeemCodes',
  },
  [Permission.RedeemCodesRedeem]: {
    value: Permission.RedeemCodesRedeem,
    group: 'commerce',
    labelKey: 'permissions.commerce.redeemCodesRedeem',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.redeemCodes',
  },
  [Permission.RiskRead]: {
    value: Permission.RiskRead,
    group: 'security',
    labelKey: 'permissions.security.riskRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.risk',
  },
  [Permission.RiskWrite]: {
    value: Permission.RiskWrite,
    group: 'security',
    labelKey: 'permissions.security.riskWrite',
    risk: 'high',
    scope: 'workspace',
    ctxCapability: 'ctx.risk',
  },
  [Permission.NotificationsRead]: {
    value: Permission.NotificationsRead,
    group: 'background',
    labelKey: 'permissions.background.notificationsRead',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.notifications',
  },
  [Permission.NotificationsSend]: {
    value: Permission.NotificationsSend,
    group: 'background',
    labelKey: 'permissions.background.notificationsSend',
    risk: 'medium',
    scope: 'workspace',
    ctxCapability: 'ctx.notifications',
  },
  [Permission.RuntimeManage]: {
    value: Permission.RuntimeManage,
    group: 'system',
    labelKey: 'permissions.system.runtimeManage',
    risk: 'critical',
    scope: 'system',
  },
  [Permission.ProductManage]: {
    value: Permission.ProductManage,
    group: 'system',
    labelKey: 'permissions.system.productManage',
    risk: 'critical',
    scope: 'product',
  },
  [Permission.AuthManage]: {
    value: Permission.AuthManage,
    group: 'system',
    labelKey: 'permissions.system.authManage',
    risk: 'critical',
    scope: 'system',
  },
  [Permission.UnsafeSqlRaw]: {
    value: Permission.UnsafeSqlRaw,
    group: 'system',
    labelKey: 'permissions.system.unsafeSqlRaw',
    risk: 'critical',
    scope: 'system',
  },
  [Permission.UnsafeInternalResource]: {
    value: Permission.UnsafeInternalResource,
    group: 'system',
    labelKey: 'permissions.system.unsafeInternalResource',
    risk: 'critical',
    scope: 'system',
    runtime: 'system',
  },
};

export const PermissionRegistryEntries = Object.values(PermissionRegistry);
