import type { ModuleContext } from '@ploykit/module-sdk';

export default async function generateReport(
  ctx: ModuleContext,
  input: { title?: string; content?: string } = {},
  run: { id: string }
) {
  const title = input.title ?? 'Workflow report';
  const artifact = await ctx.artifacts.write({
    name: 'capability-workflow-report',
    kind: 'markdown',
    runId: run.id,
    path: `runs/${run.id}/capability-workflow-report.md`,
    content: `# ${title}\n\n${input.content ?? 'Generated by capability-demo.'}`,
  });
  await ctx.usage.record({ meter: 'capability.workflow.report.generated' });

  if (ctx.user) {
    await ctx.notifications.send({
      userId: ctx.user.id,
      title: 'Workflow report ready',
      body: `Generated ${artifact.name}.`,
      runId: run.id,
    });
  }

  return {
    ok: true,
    artifactId: artifact.id,
    event: 'capability-demo.reported',
  };
}
