/**
 * Transport Layer Type Definitions
 *
 * Defines interfaces for event and service transports.
 */

/**
 * Event Transport Interface
 */
export interface EventTransport {
  /**
   * Send an event to all subscribers
   *
   * @param event - Event name
   * @param payload - Event data
   * @param metadata - Event metadata
   */
  send(event: string, payload: unknown, metadata: EventMetadata): Promise<void>;

  /**
   * Subscribe to an event
   *
   * @param event - Event name
   * @param pluginId - Plugin ID
   * @param handler - Event handler function
   */
  subscribe(event: string, pluginId: string, handler: EventHandler): void;

  /**
   * Unsubscribe from an event
   *
   * @param event - Event name
   * @param pluginId - Plugin ID
   * @param handler - Event handler function
   */
  unsubscribe(event: string, pluginId: string, handler: EventHandler): void;

  /**
   * Get all subscriber plugin IDs for an event
   *
   * @param event - Event name
   */
  getSubscribers(event: string): string[];

  /**
   * Remove all subscriptions for a plugin on a specific event
   *
   * @param pluginId - Plugin ID
   * @param event - Event name
   */
  removePluginEventSubscriptions(pluginId: string, event: string): void;

  /**
   * Get all events a plugin is subscribed to
   *
   * @param pluginId - Plugin ID
   */
  getPluginEventSubscriptions(pluginId: string): string[];

  /**
   * Remove all subscriptions for a plugin
   *
   * @param pluginId - Plugin ID
   */
  removeAllSubscriptions(pluginId: string): void;

  /**
   * Clear all subscriptions (for testing/admin)
   */
  clear?(): void;
}

/**
 * Event metadata passed to event handlers
 */
export interface EventMetadata {
  /** Plugin ID that emitted the event */
  emitterId: string;

  /** Timestamp when the event was emitted */
  timestamp: Date;

  /** Unique event envelope ID generated by the EventBus unless supplied by the caller */
  eventId: string;

  /** Correlation ID used to connect webhook -> billing -> audit chains */
  correlationId: string;

  /** Parent event ID, when this event was caused by another event */
  causationId?: string;

  /** Optional business idempotency key for at-least-once handlers */
  idempotencyKey?: string;
}

/**
 * Event handler function type
 */
export type EventHandler = (payload: unknown, metadata: EventMetadata) => void | Promise<void>;

/**
 * Service Transport Interface
 */
export interface ServiceTransport {
  /**
   * Invoke a service and wait for result
   *
   * @param service - Service name
   * @param payload - Request data
   * @param metadata - Service metadata
   * @returns Response data
   */
  invoke<T>(service: string, payload: unknown, metadata: ServiceMetadata): Promise<T>;

  /**
   * Register a service provider
   *
   * @param service - Service name
   * @param pluginId - Plugin ID
   * @param handler - Service handler function
   */
  register(service: string, pluginId: string, handler: ServiceHandler): void;

  /**
   * Unregister a service
   *
   * @param service - Service name
   */
  unregister(service: string): void;

  /**
   * Check if a service is registered
   *
   * @param service - Service name
   */
  hasService(service: string): boolean;

  /**
   * Get the provider plugin ID for a service
   *
   * @param service - Service name
   */
  getProvider(service: string): string | undefined;

  /**
   * List all registered services
   *
   * @returns Array of service names
   */
  listServices(): string[];

  /**
   * Remove all services for a plugin
   *
   * @param pluginId - Plugin ID
   */
  removeAllServices(pluginId: string): void;

  /**
   * Clear all registrations (for testing/admin)
   */
  clear?(): void;
}

/**
 * Service metadata passed to service handlers
 */
export interface ServiceMetadata {
  /** Caller plugin ID */
  callerId: string;

  /** Timeout in milliseconds */
  timeout?: number;

  /** User ID (optional) */
  userId?: string;
}

/**
 * Service handler function type
 */
export type ServiceHandler<T = unknown> = (
  payload: unknown,
  metadata: ServiceMetadata
) => T | Promise<T>;

/**
 * Available event transport types
 */
export type EventTransportType = 'auto' | 'local' | 'outbox' | 'queue';

/**
 * Available service transport types
 */
export type ServiceTransportType = 'local' | 'http' | 'grpc';
