

DROP POLICY IF EXISTS p_task_tenant_isolation ON task;
ALTER TABLE task NO FORCE ROW LEVEL SECURITY;
ALTER TABLE task DISABLE ROW LEVEL SECURITY;
DROP FUNCTION IF EXISTS app.workspace_id();
DROP FUNCTION IF EXISTS app.user_id();
DROP SCHEMA IF EXISTS app;
