-- Generated by scripts/module-data.mjs.
-- Do not edit by hand; change module.ts and run npm run data:generate.
-- Module: cms-demo
-- Schema hash: 22600f17750c37e3026ba7edaf7824c7701445db9e15adfb0b8aca24984d9eb4

create extension if not exists pgcrypto;

create table if not exists public.module_data_models (
  module_id text not null,
  model_kind text not null,
  model_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, model_kind, model_name)
);

create table if not exists public.module_data_migrations (
  module_id text primary key,
  data_version integer not null,
  migration_mode text not null,
  migration_dir text not null,
  schema_hash text not null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.module_data_grants (
  module_id text not null,
  grant_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, grant_name)
);

create table if not exists public.module_data_checks (
  module_id text not null,
  check_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, check_name)
);

insert into public.module_data_migrations
  (module_id, data_version, migration_mode, migration_dir, schema_hash)
values
  ('cms-demo', 1, 'generated', './migrations', '22600f17750c37e3026ba7edaf7824c7701445db9e15adfb0b8aca24984d9eb4')
on conflict (module_id)
do update set
  data_version = excluded.data_version,
  migration_mode = excluded.migration_mode,
  migration_dir = excluded.migration_dir,
  schema_hash = excluded.schema_hash,
  updated_at = now();

insert into public.module_data_models
  (module_id, model_kind, model_name, schema_hash, definition)
values
  ('cms-demo', 'table', 'posts', 'e8999cec7b427377d2b2803cf783d698e8ce2d51b62ce3ef0a160b70a3463698', '{"name":"posts","physicalName":"mod_cms_demo__posts","scope":"product","columns":{"title":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"slug":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"excerpt":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"body":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"status":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"draft"},"category_slug":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"seo_title":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"seo_description":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"published_at":{"kind":"timestamp","nullable":true,"primaryKey":false,"defaultRandom":false},"metadata":{"kind":"jsonb","nullable":false,"primaryKey":false,"defaultRandom":false,"default":{"source":"cms-demo"}}},"unique":[["slug"]],"indexes":[["status"],["category_slug"],["published_at"]]}'::jsonb),
  ('cms-demo', 'table', 'categories', '95ef8e11ae44d2d522a0a42e753ccdf985e578448c20410b8c31f5d4f39500c8', '{"name":"categories","physicalName":"mod_cms_demo__categories","scope":"product","columns":{"name":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"slug":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"status":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"active"},"metadata":{"kind":"jsonb","nullable":false,"primaryKey":false,"defaultRandom":false,"default":{"source":"cms-demo"}}},"unique":[["slug"]],"indexes":[["status"]]}'::jsonb),
  ('cms-demo', 'table', 'notes', 'a6b31c12608e1ffa5a760e97d34610d2a36a304fcc72a0ff8e9f7af15296dc87', '{"name":"notes","physicalName":"mod_cms_demo__notes","scope":"workspace","columns":{"title":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"body":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"status":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"draft"},"attachment_file_id":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"metadata":{"kind":"jsonb","nullable":false,"primaryKey":false,"defaultRandom":false,"default":{"source":"cms-demo"}},"published_at":{"kind":"timestamp","nullable":true,"primaryKey":false,"defaultRandom":false}},"unique":[],"indexes":[["status"],["published_at"],["attachment_file_id"]]}'::jsonb)
on conflict (module_id, model_kind, model_name)
do update set
  schema_hash = excluded.schema_hash,
  definition = excluded.definition,
  updated_at = now();

delete from public.module_data_grants where module_id = 'cms-demo';
delete from public.module_data_checks where module_id = 'cms-demo';

create table if not exists public."mod_cms_demo__posts" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "title" text not null,
  "slug" text not null,
  "excerpt" text,
  "body" text not null,
  "status" text not null default 'draft',
  "category_slug" text,
  "seo_title" text,
  "seo_description" text,
  "published_at" timestamptz,
  "metadata" jsonb not null default '{"source":"cms-demo"}'::jsonb
);

alter table public."mod_cms_demo__posts" enable row level security;
alter table public."mod_cms_demo__posts" force row level security;

create unique index if not exists "mod_cms_demo__posts__uniq_slug"
  on public."mod_cms_demo__posts" ("slug");

create index if not exists "mod_cms_demo__posts__idx_status"
  on public."mod_cms_demo__posts" ("status");

create index if not exists "mod_cms_demo__posts__idx_category_slug"
  on public."mod_cms_demo__posts" ("category_slug");

create index if not exists "mod_cms_demo__posts__idx_published_at"
  on public."mod_cms_demo__posts" ("published_at");

drop policy if exists "mod_cms_demo__posts__module_scope_policy" on public."mod_cms_demo__posts";
create policy "mod_cms_demo__posts__module_scope_policy"
  on public."mod_cms_demo__posts"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'cms-demo'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'cms-demo'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );

create table if not exists public."mod_cms_demo__categories" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "name" text not null,
  "slug" text not null,
  "status" text not null default 'active',
  "metadata" jsonb not null default '{"source":"cms-demo"}'::jsonb
);

alter table public."mod_cms_demo__categories" enable row level security;
alter table public."mod_cms_demo__categories" force row level security;

create unique index if not exists "mod_cms_demo__categories__uniq_slug"
  on public."mod_cms_demo__categories" ("slug");

create index if not exists "mod_cms_demo__categories__idx_status"
  on public."mod_cms_demo__categories" ("status");

drop policy if exists "mod_cms_demo__categories__module_scope_policy" on public."mod_cms_demo__categories";
create policy "mod_cms_demo__categories__module_scope_policy"
  on public."mod_cms_demo__categories"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'cms-demo'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'cms-demo'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );

create table if not exists public."mod_cms_demo__notes" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "title" text not null,
  "body" text,
  "status" text not null default 'draft',
  "attachment_file_id" text,
  "metadata" jsonb not null default '{"source":"cms-demo"}'::jsonb,
  "published_at" timestamptz
);

alter table public."mod_cms_demo__notes" enable row level security;
alter table public."mod_cms_demo__notes" force row level security;

create index if not exists "mod_cms_demo__notes__idx_status"
  on public."mod_cms_demo__notes" ("status");

create index if not exists "mod_cms_demo__notes__idx_published_at"
  on public."mod_cms_demo__notes" ("published_at");

create index if not exists "mod_cms_demo__notes__idx_attachment_file_id"
  on public."mod_cms_demo__notes" ("attachment_file_id");

drop policy if exists "mod_cms_demo__notes__module_scope_policy" on public."mod_cms_demo__notes";
create policy "mod_cms_demo__notes__module_scope_policy"
  on public."mod_cms_demo__notes"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'cms-demo'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'cms-demo'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );
