import fs from 'node:fs';
import path from 'node:path';
import type { Metadata } from 'next';
import {
  validateProductPresentation,
  type ProductPresentationDiagnostic,
} from '@ploykit/module-sdk/presentation';
import productPresentation from '../product.presentation';
import {
  getProductComposition,
  getProductCompositionView,
  getProductThemeRuntimeView,
} from '../apps/host-next/lib/product-composition';
import { getModuleHost } from '../apps/host-next/lib/module-host';
import { createRoutePresentationManifest } from '../apps/host-next/lib/presentation/route-presentation-manifest';
import { createBrandAssetManifest } from '../apps/host-next/lib/presentation/brand-assets';
import { resolvePagePresentation } from '../apps/host-next/lib/presentation/page-presentation';
import { localizedPath, type SupportedLanguage } from '../apps/host-next/lib/i18n';
import {
  getHostPageRegistryEntry,
  getHostPageSlotDefinition,
  listHostPageSlots,
} from '../src/lib/module-runtime/ui/host-page-registry';

const required = process.argv.includes('--required');
const projectRoot = process.cwd();
const diagnostics: ProductPresentationDiagnostic[] = [
  ...validateProductPresentation(productPresentation),
];

function addError(code: string, message: string, diagnosticPath: string, fix?: string): void {
  diagnostics.push({
    severity: 'error',
    code,
    message,
    path: diagnosticPath,
    fix,
  });
}

function addWarning(code: string, message: string, diagnosticPath: string, fix?: string): void {
  diagnostics.push({
    severity: 'warning',
    code,
    message,
    path: diagnosticPath,
    fix,
  });
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function slotParts(surfaceId: string): { pageId: string; slotId: string } | null {
  const parts = surfaceId.split(':');
  if (parts.length !== 3 || parts[0] !== 'host.page') {
    return null;
  }
  return { pageId: parts[1], slotId: parts[2] };
}

function hostPageSurfaceParts(
  surfaceId: string
): { pageId: string; slotId?: string; validShape: boolean } | null {
  const parts = surfaceId.split(':');
  if (parts[0] !== 'host.page') {
    return null;
  }
  return {
    pageId: parts[1] ?? '',
    slotId: parts.length === 3 ? parts[2] : undefined,
    validShape: parts.length === 2 || parts.length === 3,
  };
}

function createSlotRegistryMarkdown(slots: ReturnType<typeof listHostPageSlots>): string {
  const lines = [
    '# Host Page Slots',
    '',
    'Generated by `npm run presentation:manifest` / `npm run presentation:check`.',
    '',
    '| Page | Surface | Area | Slot | Modes | Default max | Responsive | Purpose |',
    '| --- | --- | --- | --- | --- | ---: | --- | --- |',
  ];
  for (const slot of slots) {
    lines.push(
      `| ${slot.pageId} | \`${slot.surfaceId}\` | ${slot.area} | ${slot.id} | ${slot.recommendedModes.join(', ')} | ${slot.defaultMaxContributions} | ${slot.responsive} | ${slot.purpose} |`
    );
  }
  lines.push('');
  return `${lines.join('\n')}\n`;
}

function readSource(relativePath: string): string | undefined {
  const absolutePath = path.join(projectRoot, relativePath);
  if (!fs.existsSync(absolutePath)) {
    return undefined;
  }
  return fs.readFileSync(absolutePath, 'utf8');
}

function collectSourceFiles(relativeRoot: string): string[] {
  const root = path.join(projectRoot, relativeRoot);
  if (!fs.existsSync(root)) {
    return [];
  }
  const files: string[] = [];
  const visit = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (entry.isDirectory()) {
        if (!['.next', '.runtime', 'node_modules'].includes(entry.name)) {
          visit(path.join(dir, entry.name));
        }
        continue;
      }
      const ext = path.extname(entry.name);
      if (['.ts', '.tsx', '.js', '.jsx', '.mjs'].includes(ext)) {
        files.push(path.relative(projectRoot, path.join(dir, entry.name)).replace(/\\/g, '/'));
      }
    }
  };
  visit(root);
  return files;
}

function normalizeRoutePath(routePath: string): string {
  const normalized = routePath.replace(/\\/g, '/').replace(/\/+/g, '/');
  const withoutTrailingSlash =
    normalized.length > 1 ? normalized.replace(/\/+$/, '') : normalized;
  return withoutTrailingSlash || '/';
}

function nextRouteSegment(segment: string): string | null {
  if (segment.startsWith('(') && segment.endsWith(')')) {
    return null;
  }
  const optionalCatchAll = segment.match(/^\[\[\.\.\.([^\]]+)\]\]$/);
  if (optionalCatchAll) {
    return `:${optionalCatchAll[1]}*`;
  }
  const catchAll = segment.match(/^\[\.\.\.([^\]]+)\]$/);
  if (catchAll) {
    return `:${catchAll[1]}*`;
  }
  const dynamic = segment.match(/^\[([^\]]+)\]$/);
  if (dynamic) {
    return `:${dynamic[1]}`;
  }
  return segment;
}

function collectLocalizedAppPageRoutes(): string[] {
  const root = path.join(projectRoot, 'apps', 'host-next', 'app', '[lang]');
  if (!fs.existsSync(root)) {
    return [];
  }
  const routes: string[] = [];
  const visit = (dir: string) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const absolutePath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        visit(absolutePath);
        continue;
      }
      if (entry.name !== 'page.tsx') {
        continue;
      }
      const relativeDir = path.relative(root, dir);
      const segments = relativeDir
        ? relativeDir
            .split(path.sep)
            .map(nextRouteSegment)
            .filter((segment): segment is string => Boolean(segment))
        : [];
      routes.push(normalizeRoutePath(`/${segments.join('/')}`));
    }
  };
  visit(root);
  return [...new Set(routes)].sort();
}

function metadataRobotsIndex(metadata: Metadata): boolean {
  const robots = metadata.robots;
  if (typeof robots === 'object' && robots !== null && 'index' in robots) {
    return (robots as { index?: boolean }).index !== false;
  }
  return true;
}

function metadataCanonical(metadata: Metadata): string | null {
  const alternates = metadata.alternates as { canonical?: unknown } | null | undefined;
  return typeof alternates?.canonical === 'string' ? alternates.canonical : null;
}

const oldCompositionConfig = path.join(projectRoot, 'product-composition.config.json');
if (fs.existsSync(oldCompositionConfig)) {
  addError(
    'PRESENTATION_LEGACY_CONFIG_PRESENT',
    'product-composition.config.json is not allowed in the clean Product Presentation path.',
    'product-composition.config.json',
    'Move product identity, theme, pages, slots, languages, and brand assets to product.presentation.ts.'
  );
}

for (const relativePath of collectSourceFiles('apps/host-next')) {
  if (relativePath.endsWith('lib/i18n.ts')) {
    continue;
  }
  if (readSource(relativePath)?.includes('localized(')) {
    addError(
      'PRESENTATION_INLINE_LOCALIZED_PRESENT',
      'Host pages must not use inline localized(...) copy in the Product Presentation path.',
      relativePath,
      'Move copy into apps/host-next/locales/*.json or module locale resources.'
    );
  }
}

for (const relativePath of [
  'apps/host-next/lib/site-navigation.ts',
  'apps/host-next/lib/admin-operations.ts',
  'apps/host-next/app/(dashboard)/dashboard/[[...modulePath]]/page.tsx',
]) {
  if (readSource(relativePath)?.includes('fallbackLabel')) {
    addError(
      'PRESENTATION_FALLBACK_LABEL_RENDER_PATH',
      'fallbackLabel must not be used by normal host rendering paths.',
      relativePath,
      'Render navigation from labelKey + locale resources and keep fallbackLabel only for diagnostics.'
    );
  }
}

const host = await getModuleHost();
const composition = getProductComposition();
const compositionView = await getProductCompositionView();
const theme = getProductThemeRuntimeView();
const routeManifest = createRoutePresentationManifest();
const brandAssets = createBrandAssetManifest();
const slotRegistry = listHostPageSlots();
const appPageRoutes = collectLocalizedAppPageRoutes();
const manifestRoutePaths = new Set(
  routeManifest.routes.map((route) => normalizeRoutePath(route.path))
);
const appPageRouteSet = new Set(appPageRoutes);
const knownModules = new Set(host.runtime.contracts.map((contract) => contract.id));
const enabledModules = new Set(composition.enabledModules ?? host.runtime.contracts.map((contract) => contract.id));
const defaultLanguage = productPresentation.definition.defaultLanguage as SupportedLanguage;
const routeSafety: Array<{
  pageId: string;
  path: string;
  area: string;
  access: string;
  cache: unknown;
  robotsIndex: boolean;
  sitemap: boolean;
  canonical: string | null;
  activeOverride: string | null;
  diagnostics: readonly string[];
}> = [];

diagnostics.push(...brandAssets.diagnostics);

for (const appRoute of appPageRoutes) {
  if (!manifestRoutePaths.has(appRoute)) {
    addError(
      'ROUTE_PRESENTATION_APP_ROUTE_UNREGISTERED',
      `App route "${appRoute}" exists under apps/host-next/app/[lang] but is missing from route presentation manifest.`,
      `app.[lang]${appRoute === '/' ? '' : appRoute}`,
      'Register the host page id and explicit route path in HOST_PAGE_REGISTRY and HOST_ROUTE_PATH_BY_PAGE_ID.'
    );
  }
}

for (const route of routeManifest.routes) {
  const normalizedPath = normalizeRoutePath(route.path);
  if (!appPageRouteSet.has(normalizedPath)) {
    addError(
      'ROUTE_PRESENTATION_APP_ROUTE_MISSING',
      `Route presentation manifest declares "${route.path}" for "${route.pageId}", but no matching app/[lang] page exists.`,
      `routes.${route.pageId}.path`,
      'Create the Next app page or remove the stale route presentation entry.'
    );
  }
}

for (const [area, pages] of Object.entries(productPresentation.definition.pages ?? {})) {
  for (const [pageName, page] of Object.entries(pages ?? {})) {
    const pageId = `${area}.${pageName}`;
    const registryEntry = getHostPageRegistryEntry(pageId);
    if (!registryEntry) {
      addError(
        'PRESENTATION_PAGE_UNKNOWN',
        `Product presentation references unknown host page "${pageId}".`,
        `pages.${pageId}`,
        'Use a page id from the host page registry.'
      );
      continue;
    }
    if (page.mode === 'host' && page.replaceWith) {
      addError(
        'PRESENTATION_PAGE_HOST_MODE_REPLACE_CONFLICT',
        `Host page "${pageId}" uses mode: "host" but also declares replaceWith.`,
        `pages.${pageId}.replaceWith`,
        'Remove replaceWith or set mode: "replace".'
      );
    }
    if (page.replaceWith && !knownModules.has(page.replaceWith)) {
      addError(
        'PRESENTATION_PAGE_REPLACE_MODULE_UNKNOWN',
        `Host page "${pageId}" references unknown module "${page.replaceWith}".`,
        `pages.${pageId}.replaceWith`,
        'Use an installed module id.'
      );
    }
    if (page.replaceWith && !enabledModules.has(page.replaceWith)) {
      addError(
        'PRESENTATION_PAGE_REPLACE_MODULE_DISABLED',
        `Host page "${pageId}" references disabled module "${page.replaceWith}".`,
        `pages.${pageId}.replaceWith`,
        'Add the module to modules.enabled or remove the override.'
      );
    }
    if (
      page.replaceWith &&
      page.mode !== 'disabled' &&
      registryEntry.replacePolicy === 'controlled' &&
      page.mode !== 'replace'
    ) {
      addError(
        'PRESENTATION_CONTROLLED_PAGE_REPLACE_MODE_REQUIRED',
        `Controlled host page "${pageId}" requires mode: "replace" before replacement is enabled.`,
        `pages.${pageId}.mode`,
        'Set mode: "replace" for intentional auth/dashboard/admin replacements.'
      );
    }
  }
}

for (const [surfaceId, policy] of Object.entries(composition.slotPolicies ?? {})) {
  const parsed = slotParts(surfaceId);
  if (!parsed) {
    addError(
      'PRESENTATION_SLOT_SURFACE_INVALID',
      `Slot policy "${surfaceId}" must target a concrete host page slot.`,
      `slots.${surfaceId}`,
      'Use a surface id like "host.page:site.home:hero".'
    );
    continue;
  }
  const registryEntry = getHostPageRegistryEntry(parsed.pageId);
  if (!registryEntry) {
    addError(
      'PRESENTATION_SLOT_PAGE_UNKNOWN',
      `Slot policy "${surfaceId}" references unknown host page "${parsed.pageId}".`,
      `slots.${surfaceId}`,
      'Use a page id from the host page registry.'
    );
    continue;
  }
  if (!registryEntry.slots.includes(parsed.slotId)) {
    addError(
      'PRESENTATION_SLOT_ID_UNKNOWN',
      `Slot policy "${surfaceId}" references unknown slot "${parsed.slotId}" on "${parsed.pageId}".`,
      `slots.${surfaceId}`,
      `Use one of: ${registryEntry.slots.join(', ')}.`
    );
  }
  for (const moduleId of [...(policy.allowModules ?? []), ...(policy.denyModules ?? [])]) {
    if (!knownModules.has(moduleId)) {
      addError(
        'PRESENTATION_SLOT_MODULE_UNKNOWN',
        `Slot policy "${surfaceId}" references unknown module "${moduleId}".`,
        `slots.${surfaceId}`,
        'Use an installed module id.'
      );
    }
  }
}

for (const route of routeManifest.routes) {
  if (!route.path.startsWith('/')) {
    addError(
      'ROUTE_PRESENTATION_PATH_INVALID',
      `Route presentation path "${route.path}" must start with "/".`,
      `routes.${route.pageId}.path`
    );
  }
  if (!route.metadata.pageKey.trim()) {
    addError(
      'ROUTE_PRESENTATION_PAGE_KEY_MISSING',
      `Route "${route.pageId}" must expose a metadata pageKey.`,
      `routes.${route.pageId}.metadata.pageKey`
    );
  }
  if (route.area === 'site' && route.access !== 'public') {
    addError(
      'ROUTE_PRESENTATION_SITE_ACCESS_INVALID',
      `Site route "${route.pageId}" must be public.`,
      `routes.${route.pageId}.access`
    );
  }
  if (route.area === 'dashboard' && route.access !== 'auth') {
    addError(
      'ROUTE_PRESENTATION_DASHBOARD_ACCESS_INVALID',
      `Dashboard route "${route.pageId}" must require auth.`,
      `routes.${route.pageId}.access`
    );
  }
  if ((route.area === 'admin' || route.area === 'dev') && route.access !== 'admin') {
    addError(
      'ROUTE_PRESENTATION_ADMIN_ACCESS_INVALID',
      `Admin route "${route.pageId}" must require admin access.`,
      `routes.${route.pageId}.access`
    );
  }
  for (const slotId of route.slots) {
    const surfaceId = `host.page:${route.pageId}:${slotId}`;
    const policy = composition.slotPolicies?.[surfaceId];
    if (policy?.maxContributions !== undefined && policy.maxContributions < 1) {
      addError(
        'ROUTE_PRESENTATION_SLOT_MAX_INVALID',
        `Slot "${surfaceId}" maxContributions must be positive.`,
        `slots.${surfaceId}.maxContributions`
      );
    }
  }
  try {
    const presentation = await resolvePagePresentation({
      pageId: route.pageId,
      pathname: localizedPath(defaultLanguage, route.path),
      lang: defaultLanguage,
    });
    const robotsIndex = metadataRobotsIndex(presentation.seo);
    const canonical = metadataCanonical(presentation.seo);
    routeSafety.push({
      pageId: route.pageId,
      path: route.path,
      area: route.area,
      access: route.access,
      cache: presentation.cache,
      robotsIndex,
      sitemap: route.area === 'site',
      canonical,
      activeOverride: presentation.activeModuleId,
      diagnostics: presentation.diagnostics.map((item) => item.code),
    });
    if (route.area !== 'site' && robotsIndex) {
      addError(
        'ROUTE_PRESENTATION_PRIVATE_ROUTE_INDEXABLE',
        `Non-site route "${route.pageId}" must be noindex.`,
        `routes.${route.pageId}.robots`
      );
    }
    if (route.area !== 'site' && presentation.cache.mode === 'public') {
      addError(
        'ROUTE_PRESENTATION_PRIVATE_CACHE_PUBLIC',
        `Non-site route "${route.pageId}" must not use public cache.`,
        `routes.${route.pageId}.cache`
      );
    }
    if (route.area === 'site' && !canonical) {
      addError(
        'ROUTE_PRESENTATION_CANONICAL_MISSING',
        `Site route "${route.pageId}" must expose a canonical URL.`,
        `routes.${route.pageId}.canonical`
      );
    }
    for (const item of presentation.diagnostics) {
      const code = `PAGE_PRESENTATION_${item.code}`;
      const diagnosticPath = `pages.${route.pageId}.diagnostics.${item.code}`;
      if (item.severity === 'error') {
        addError(code, item.message, diagnosticPath);
      } else if (item.severity === 'warning') {
        addWarning(code, item.message, diagnosticPath);
      }
    }
  } catch (error) {
    addError(
      'PAGE_PRESENTATION_RESOLVE_FAILED',
      `Route "${route.pageId}" failed to resolve page presentation: ${errorMessage(error)}`,
      `pages.${route.pageId}`
    );
  }
}

for (const contribution of host.runtime.surfaces.list()) {
  const parsed = hostPageSurfaceParts(contribution.surfaceId);
  if (!parsed) {
    continue;
  }
  if (!parsed.validShape || !parsed.pageId) {
    addError(
      'PRESENTATION_MODULE_HOST_PAGE_SURFACE_INVALID',
      `Module "${contribution.moduleId}" declares invalid host page surface "${contribution.surfaceId}".`,
      `modules.${contribution.moduleId}.surfaces.${contribution.surfaceId}`,
      'Use "host.page:<pageId>" for replacement or "host.page:<pageId>:<slotId>" for slot contribution.'
    );
    continue;
  }
  const registryEntry = getHostPageRegistryEntry(parsed.pageId);
  if (!registryEntry) {
    addError(
      'PRESENTATION_MODULE_HOST_PAGE_UNKNOWN',
      `Module "${contribution.moduleId}" targets unknown host page "${parsed.pageId}".`,
      `modules.${contribution.moduleId}.surfaces.${contribution.surfaceId}`,
      'Use a page id from the host page registry.'
    );
    continue;
  }
  if (!parsed.slotId) {
    continue;
  }
  if (!registryEntry.slots.includes(parsed.slotId)) {
    addError(
      'PRESENTATION_MODULE_SLOT_ID_UNKNOWN',
      `Module "${contribution.moduleId}" targets unknown slot "${parsed.slotId}" on "${parsed.pageId}".`,
      `modules.${contribution.moduleId}.surfaces.${contribution.surfaceId}`,
      `Use one of: ${registryEntry.slots.join(', ')}.`
    );
    continue;
  }
  if (contribution.definition.mode === 'replace') {
    addError(
      'PRESENTATION_MODULE_SLOT_REPLACE_INVALID',
      `Module "${contribution.moduleId}" uses replace mode on slot "${contribution.surfaceId}".`,
      `modules.${contribution.moduleId}.surfaces.${contribution.surfaceId}.mode`,
      'Use replace only on whole host.page surfaces, not host.page slots.'
    );
    continue;
  }
  const slotDefinition = getHostPageSlotDefinition(parsed.slotId);
  const mode = contribution.definition.mode ?? 'append';
  if (!slotDefinition.recommendedModes.includes(mode)) {
    addWarning(
      'PRESENTATION_MODULE_SLOT_MODE_NOT_RECOMMENDED',
      `Module "${contribution.moduleId}" uses mode "${mode}" on "${contribution.surfaceId}", outside the slot recommendation.`,
      `modules.${contribution.moduleId}.surfaces.${contribution.surfaceId}.mode`,
      `Recommended modes: ${slotDefinition.recommendedModes.join(', ')}.`
    );
  }
}

for (const page of compositionView.pages) {
  for (const item of page.diagnostics) {
    addError(
      'PRESENTATION_PAGE_COMPOSITION_DIAGNOSTIC',
      item,
      `pages.${page.pageId}.diagnostics`
    );
  }
}

for (const slot of compositionView.slots) {
  for (const item of slot.diagnostics) {
    addError(
      'PRESENTATION_SLOT_POLICY_DIAGNOSTIC',
      item,
      `slots.${slot.surfaceId}.diagnostics`
    );
  }
}

const manifest = {
  kind: 'ploykit.product-presentation.manifest',
  checkedAt: new Date().toISOString(),
  product: {
    id: productPresentation.definition.id,
    name: productPresentation.definition.name,
    defaultLanguage: productPresentation.definition.defaultLanguage,
    supportedLanguages: productPresentation.definition.supportedLanguages,
  },
  modules: {
    enabled: composition.enabledModules ?? [],
  },
  pages: Object.fromEntries(
    Object.entries(composition.pageOverrides ?? {}).map(([pageId, override]) => [
      pageId,
      {
        moduleId: override.moduleId,
        enabled: override.enabled,
      },
    ])
  ),
  slots: Object.keys(composition.slotPolicies ?? {}).sort(),
  slotRegistry,
  compositionSlots: compositionView.slots.map((slot) => ({
    pageId: slot.pageId,
    slotId: slot.slotId,
    surfaceId: slot.surfaceId,
    configured: slot.configured,
    maxContributions: slot.maxContributions,
    effectiveMaxContributions: slot.effectiveMaxContributions,
    candidateModules: slot.candidateModules,
    activeModules: slot.activeModules,
    blockedContributions: slot.blockedContributions,
    diagnostics: slot.diagnostics,
  })),
  routes: routeManifest.routes,
  appRoutes: appPageRoutes,
  routeSafety,
  brandAssets,
  moduleRoutes: host.runtime.routes
    .filter((route) => route.kind === 'site')
    .map((route) => ({
      moduleId: route.moduleId,
      path: route.path,
      canonicalPath: route.canonicalPath,
      source: route.source,
      auth: route.auth,
      cache:
        'cache' in route.route && route.route.cache
          ? {
              strategy: route.route.cache.strategy,
              revalidateSeconds: route.route.cache.revalidateSeconds,
              tags: route.route.cache.tags,
            }
          : null,
    }))
    .sort((left, right) =>
      `${left.moduleId}:${left.path}`.localeCompare(`${right.moduleId}:${right.path}`)
    ),
  theme: {
    profileId: theme.product.themeProfileId,
    profileName: theme.product.profileName,
    acceptedTokens: Object.keys(theme.product.acceptedTokens).sort(),
    rejectedTokens: Object.keys(theme.product.rejectedTokens).sort(),
    acceptedDarkTokens: Object.keys(theme.product.acceptedDarkTokens).sort(),
    rejectedDarkTokens: Object.keys(theme.product.rejectedDarkTokens).sort(),
  },
  diagnostics,
};

const outputPaths = [
  path.join(projectRoot, '.runtime', 'product-presentation-manifest.json'),
  path.join(projectRoot, '.ploykit', 'generated', 'product-presentation.manifest.json'),
];
for (const outputPath of outputPaths) {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, `${JSON.stringify(manifest, null, 2)}\n`);
}

const markdownOutputPaths = [
  path.join(projectRoot, '.runtime', 'host-page-slots.md'),
  path.join(projectRoot, '.ploykit', 'generated', 'host-page-slots.md'),
];
const slotRegistryMarkdown = createSlotRegistryMarkdown(slotRegistry);
for (const outputPath of markdownOutputPaths) {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, slotRegistryMarkdown);
}

const ok = diagnostics.every((item) => item.severity !== 'error');
const result = {
  ok: required ? ok : true,
  required,
  outputPath: outputPaths[0],
  outputPaths,
  markdownOutputPaths,
  diagnostics,
};

process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
process.exitCode = result.ok ? 0 : 1;
