import type { ModuleContext } from '@ploykit/module-sdk';

export default async function generateReport(
  ctx: ModuleContext,
  input: { title?: string; content?: string } = {},
  run: { id: string }
) {
  const title = input.title ?? 'Platform smoke report';
  const artifact = await ctx.artifacts.write({
    name: 'platform-smoke-report',
    kind: 'markdown',
    runId: run.id,
    path: `runs/${run.id}/platform-smoke-report.md`,
    content: `# ${title}\n\n${input.content ?? 'Generated by platform-smoke.'}`,
  });
  await ctx.usage.record({ meter: 'platform-smoke.report.generated' });
  await ctx.audit.record('platform-smoke.report.generated', {
    runId: run.id,
    artifactId: artifact.id,
  });

  if (ctx.user) {
    await ctx.notifications.send({
      userId: ctx.user.id,
      title: 'Platform smoke report ready',
      body: `Generated ${artifact.name}.`,
      runId: run.id,
    });
  }

  return {
    ok: true,
    artifactId: artifact.id,
    event: 'platform-smoke.reported',
  };
}
