import type { ModuleContext } from '@ploykit/module-sdk';

export default async function generateReport(
  ctx: ModuleContext,
  input: { title?: string; content?: string } = {},
  run: { id: string }
) {
  const title = input.title ?? 'Platform smoke report';
  const artifact = await ctx.files.createUpload({
    name: 'platform-smoke-report.md',
    purpose: 'result',
    contentType: 'text/markdown',
    metadata: { title, content: input.content ?? 'Generated by platform-smoke.', runId: run.id },
  });
  await ctx.audit.record('platform-smoke.report.generated', {
    runId: run.id,
    artifactId: artifact.file.id,
  });

  if (ctx.user) {
    await ctx.notifications.send({
      userId: ctx.user.id,
      title: 'Platform smoke report ready',
      body: `Generated ${artifact.file.name}.`,
      runId: run.id,
    });
  }

  return {
    ok: true,
    artifactId: artifact.file.id,
    event: 'platform-smoke.reported',
  };
}
