-- Generated by scripts/module-data.mjs.
-- Do not edit by hand; change module.ts and run npm run data:generate.
-- Module: shop-demo
-- Schema hash: 0f4752512b9c3fda17291557f99a85a35d6c5ffb6e05e9950002edc6e1c7d0bc

create extension if not exists pgcrypto;

create table if not exists public.module_data_models (
  module_id text not null,
  model_kind text not null,
  model_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, model_kind, model_name)
);

create table if not exists public.module_data_migrations (
  module_id text primary key,
  data_version integer not null,
  migration_mode text not null,
  migration_dir text not null,
  schema_hash text not null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.module_data_grants (
  module_id text not null,
  grant_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, grant_name)
);

create table if not exists public.module_data_checks (
  module_id text not null,
  check_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, check_name)
);

insert into public.module_data_migrations
  (module_id, data_version, migration_mode, migration_dir, schema_hash)
values
  ('shop-demo', 1, 'generated', './migrations', '0f4752512b9c3fda17291557f99a85a35d6c5ffb6e05e9950002edc6e1c7d0bc')
on conflict (module_id)
do update set
  data_version = excluded.data_version,
  migration_mode = excluded.migration_mode,
  migration_dir = excluded.migration_dir,
  schema_hash = excluded.schema_hash,
  updated_at = now();

insert into public.module_data_models
  (module_id, model_kind, model_name, schema_hash, definition)
values
  ('shop-demo', 'table', 'products', 'f4c1bcb08d0d9c4a8de8da5ac69e90bdf2e73b1756abb59372fea845b1202d1a', '{"name":"products","physicalName":"mod_shop_demo__products","scope":"product","columns":{"sku":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"title":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"slug":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"description":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"status":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"active"},"price_cents":{"kind":"integer","nullable":false,"primaryKey":false,"defaultRandom":false},"currency":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"usd"},"inventory":{"kind":"integer","nullable":false,"primaryKey":false,"defaultRandom":false,"default":0},"metadata":{"kind":"jsonb","nullable":false,"primaryKey":false,"defaultRandom":false,"default":{"source":"shop-demo"}}},"unique":[["sku"],["slug"]],"indexes":[["status"],["inventory"]]}'::jsonb),
  ('shop-demo', 'table', 'coupons', '092b7f542fb2bea29df24dd4a4f53a5ebd15a9c9d2b82b40b1cff565cdb18b5f', '{"name":"coupons","physicalName":"mod_shop_demo__coupons","scope":"product","columns":{"code":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"percent_off":{"kind":"integer","nullable":false,"primaryKey":false,"defaultRandom":false,"default":0},"status":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"active"},"expires_at":{"kind":"timestamp","nullable":true,"primaryKey":false,"defaultRandom":false},"metadata":{"kind":"jsonb","nullable":false,"primaryKey":false,"defaultRandom":false,"default":{"source":"shop-demo"}}},"unique":[["code"]],"indexes":[["status"],["expires_at"]]}'::jsonb),
  ('shop-demo', 'table', 'orders', 'a59781c7e16749c2cca8735f6e4119d3fe2d8bdcbcbd6ec582c8bebb0edd19d6', '{"name":"orders","physicalName":"mod_shop_demo__orders","scope":"product","columns":{"order_number":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"user_id":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"sku":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"product_title":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"quantity":{"kind":"integer","nullable":false,"primaryKey":false,"defaultRandom":false,"default":1},"subtotal_cents":{"kind":"integer","nullable":false,"primaryKey":false,"defaultRandom":false},"discount_cents":{"kind":"integer","nullable":false,"primaryKey":false,"defaultRandom":false,"default":0},"total_cents":{"kind":"integer","nullable":false,"primaryKey":false,"defaultRandom":false},"currency":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"usd"},"status":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"checkout_created"},"checkout_id":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"coupon_code":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"metadata":{"kind":"jsonb","nullable":false,"primaryKey":false,"defaultRandom":false,"default":{"source":"shop-demo"}}},"unique":[["order_number"]],"indexes":[["user_id"],["sku"],["status"]]}'::jsonb)
on conflict (module_id, model_kind, model_name)
do update set
  schema_hash = excluded.schema_hash,
  definition = excluded.definition,
  updated_at = now();

delete from public.module_data_grants where module_id = 'shop-demo';
delete from public.module_data_checks where module_id = 'shop-demo';

create table if not exists public."mod_shop_demo__products" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "sku" text not null,
  "title" text not null,
  "slug" text not null,
  "description" text,
  "status" text not null default 'active',
  "price_cents" integer not null,
  "currency" text not null default 'usd',
  "inventory" integer not null default 0,
  "metadata" jsonb not null default '{"source":"shop-demo"}'::jsonb
);

alter table public."mod_shop_demo__products" enable row level security;
alter table public."mod_shop_demo__products" force row level security;

create unique index if not exists "mod_shop_demo__products__uniq_sku"
  on public."mod_shop_demo__products" ("sku");

create unique index if not exists "mod_shop_demo__products__uniq_slug"
  on public."mod_shop_demo__products" ("slug");

create index if not exists "mod_shop_demo__products__idx_status"
  on public."mod_shop_demo__products" ("status");

create index if not exists "mod_shop_demo__products__idx_inventory"
  on public."mod_shop_demo__products" ("inventory");

drop policy if exists "mod_shop_demo__products__module_scope_policy" on public."mod_shop_demo__products";
create policy "mod_shop_demo__products__module_scope_policy"
  on public."mod_shop_demo__products"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'shop-demo'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'shop-demo'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );

create table if not exists public."mod_shop_demo__coupons" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "code" text not null,
  "percent_off" integer not null default 0,
  "status" text not null default 'active',
  "expires_at" timestamptz,
  "metadata" jsonb not null default '{"source":"shop-demo"}'::jsonb
);

alter table public."mod_shop_demo__coupons" enable row level security;
alter table public."mod_shop_demo__coupons" force row level security;

create unique index if not exists "mod_shop_demo__coupons__uniq_code"
  on public."mod_shop_demo__coupons" ("code");

create index if not exists "mod_shop_demo__coupons__idx_status"
  on public."mod_shop_demo__coupons" ("status");

create index if not exists "mod_shop_demo__coupons__idx_expires_at"
  on public."mod_shop_demo__coupons" ("expires_at");

drop policy if exists "mod_shop_demo__coupons__module_scope_policy" on public."mod_shop_demo__coupons";
create policy "mod_shop_demo__coupons__module_scope_policy"
  on public."mod_shop_demo__coupons"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'shop-demo'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'shop-demo'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );

create table if not exists public."mod_shop_demo__orders" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "order_number" text not null,
  "user_id" text not null,
  "sku" text not null,
  "product_title" text not null,
  "quantity" integer not null default 1,
  "subtotal_cents" integer not null,
  "discount_cents" integer not null default 0,
  "total_cents" integer not null,
  "currency" text not null default 'usd',
  "status" text not null default 'checkout_created',
  "checkout_id" text,
  "coupon_code" text,
  "metadata" jsonb not null default '{"source":"shop-demo"}'::jsonb
);

alter table public."mod_shop_demo__orders" enable row level security;
alter table public."mod_shop_demo__orders" force row level security;

create unique index if not exists "mod_shop_demo__orders__uniq_order_number"
  on public."mod_shop_demo__orders" ("order_number");

create index if not exists "mod_shop_demo__orders__idx_user_id"
  on public."mod_shop_demo__orders" ("user_id");

create index if not exists "mod_shop_demo__orders__idx_sku"
  on public."mod_shop_demo__orders" ("sku");

create index if not exists "mod_shop_demo__orders__idx_status"
  on public."mod_shop_demo__orders" ("status");

drop policy if exists "mod_shop_demo__orders__module_scope_policy" on public."mod_shop_demo__orders";
create policy "mod_shop_demo__orders__module_scope_policy"
  on public."mod_shop_demo__orders"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'shop-demo'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'shop-demo'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );
