-- Generated by scripts/module-data.mjs.
-- Do not edit by hand; change module.ts and run npm run data:generate.
-- Module: resource-smoke
-- Schema hash: 61d0cd138f15edb6fe0bffdb9da942a368dc5fd60b42d190bc5dbae7f559415c

create extension if not exists pgcrypto;

create table if not exists public.module_documents (
  id uuid primary key default gen_random_uuid(),
  product_id text not null,
  module_id text not null,
  scope_type text not null,
  scope_id text,
  document_name text not null,
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by text,
  updated_by text
);

create index if not exists module_documents__module_document_scope_idx
  on public.module_documents (product_id, module_id, document_name, scope_type, scope_id);

alter table public.module_documents enable row level security;
alter table public.module_documents force row level security;

drop policy if exists module_documents__module_scope_policy on public.module_documents;
create policy module_documents__module_scope_policy
  on public.module_documents
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = current_setting('ploykit.module_id', true)
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = current_setting('ploykit.module_id', true)
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );

create table if not exists public.module_data_models (
  module_id text not null,
  model_kind text not null,
  model_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, model_kind, model_name)
);

create table if not exists public.module_data_migrations (
  module_id text primary key,
  data_version integer not null,
  migration_mode text not null,
  migration_dir text not null,
  schema_hash text not null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.module_data_grants (
  module_id text not null,
  grant_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, grant_name)
);

create table if not exists public.module_data_checks (
  module_id text not null,
  check_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, check_name)
);

insert into public.module_data_migrations
  (module_id, data_version, migration_mode, migration_dir, schema_hash)
values
  ('resource-smoke', 1, 'generated', './migrations', '61d0cd138f15edb6fe0bffdb9da942a368dc5fd60b42d190bc5dbae7f559415c')
on conflict (module_id)
do update set
  data_version = excluded.data_version,
  migration_mode = excluded.migration_mode,
  migration_dir = excluded.migration_dir,
  schema_hash = excluded.schema_hash,
  updated_at = now();

insert into public.module_data_models
  (module_id, model_kind, model_name, schema_hash, definition)
values
  ('resource-smoke', 'document', 'user_notes', 'c51c0831c5d3942b9edf7f741d2c858a3a9124ba53e26db2cd6a35392bd53f70', '{"name":"user_notes","scope":"user","fields":{"message":{"type":"string","required":true,"maxLength":200}}}'::jsonb),
  ('resource-smoke', 'table', 'workspace_notes', 'a61c2edbada48803484320887a6c45f9a692d4ccea8dce73f56556c34c7a2bad', '{"name":"workspace_notes","physicalName":"mod_resource_smoke__workspace_notes","scope":"workspace","columns":{"title":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"body":{"kind":"text","nullable":true,"primaryKey":false,"defaultRandom":false},"status":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"draft"}},"unique":[],"indexes":[["status"]]}'::jsonb),
  ('resource-smoke', 'table', 'public_posts', '4f6fb7d798af0917e859dae91ae47d59300dfac5cb98785032b31f59a31e23be', '{"name":"public_posts","physicalName":"mod_resource_smoke__public_posts","scope":"public-read","columns":{"title":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"status":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false,"default":"draft"},"metadata":{"kind":"jsonb","nullable":false,"primaryKey":false,"defaultRandom":false,"default":{"featured":false}}},"unique":[["title"]],"indexes":[["status"]]}'::jsonb),
  ('resource-smoke', 'table', 'product_items', 'b6f8b939c7291a91702989e5a36c05279cf131b08c2bc969cdf794fb3066a8cc', '{"name":"product_items","physicalName":"mod_resource_smoke__product_items","scope":"product","columns":{"sku":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"title":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"price_cents":{"kind":"integer","nullable":false,"primaryKey":false,"defaultRandom":false},"inventory":{"kind":"integer","nullable":false,"primaryKey":false,"defaultRandom":false,"default":0},"metadata":{"kind":"jsonb","nullable":false,"primaryKey":false,"defaultRandom":false,"default":{"source":"resource-smoke"}}},"unique":[["sku"]],"indexes":[["inventory"]]}'::jsonb)
on conflict (module_id, model_kind, model_name)
do update set
  schema_hash = excluded.schema_hash,
  definition = excluded.definition,
  updated_at = now();

delete from public.module_data_grants where module_id = 'resource-smoke';
delete from public.module_data_checks where module_id = 'resource-smoke';

create table if not exists public."mod_resource_smoke__workspace_notes" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "title" text not null,
  "body" text,
  "status" text not null default 'draft'
);

alter table public."mod_resource_smoke__workspace_notes" enable row level security;
alter table public."mod_resource_smoke__workspace_notes" force row level security;

create index if not exists "mod_resource_smoke__workspace_notes__idx_status"
  on public."mod_resource_smoke__workspace_notes" ("status");

drop policy if exists "mod_resource_smoke__workspace_notes__module_scope_policy" on public."mod_resource_smoke__workspace_notes";
create policy "mod_resource_smoke__workspace_notes__module_scope_policy"
  on public."mod_resource_smoke__workspace_notes"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'resource-smoke'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'resource-smoke'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );

create table if not exists public."mod_resource_smoke__public_posts" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "title" text not null,
  "status" text not null default 'draft',
  "metadata" jsonb not null default '{"featured":false}'::jsonb
);

alter table public."mod_resource_smoke__public_posts" enable row level security;
alter table public."mod_resource_smoke__public_posts" force row level security;

create unique index if not exists "mod_resource_smoke__public_posts__uniq_title"
  on public."mod_resource_smoke__public_posts" ("title");

create index if not exists "mod_resource_smoke__public_posts__idx_status"
  on public."mod_resource_smoke__public_posts" ("status");

drop policy if exists "mod_resource_smoke__public_posts__module_scope_policy" on public."mod_resource_smoke__public_posts";
create policy "mod_resource_smoke__public_posts__module_scope_policy"
  on public."mod_resource_smoke__public_posts"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'resource-smoke'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'resource-smoke'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );

create table if not exists public."mod_resource_smoke__product_items" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "sku" text not null,
  "title" text not null,
  "price_cents" integer not null,
  "inventory" integer not null default 0,
  "metadata" jsonb not null default '{"source":"resource-smoke"}'::jsonb
);

alter table public."mod_resource_smoke__product_items" enable row level security;
alter table public."mod_resource_smoke__product_items" force row level security;

create unique index if not exists "mod_resource_smoke__product_items__uniq_sku"
  on public."mod_resource_smoke__product_items" ("sku");

create index if not exists "mod_resource_smoke__product_items__idx_inventory"
  on public."mod_resource_smoke__product_items" ("inventory");

drop policy if exists "mod_resource_smoke__product_items__module_scope_policy" on public."mod_resource_smoke__product_items";
create policy "mod_resource_smoke__product_items__module_scope_policy"
  on public."mod_resource_smoke__product_items"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'resource-smoke'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'resource-smoke'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );
