-- Generated by scripts/module-data.mjs.
-- Do not edit by hand; change module.ts and run npm run data:generate.
-- Module: capability-demo
-- Schema hash: e3ccbd23fadf13eda61dc24eb7e002c498d517dc5fd3239afe01163d7cb4583a

create extension if not exists pgcrypto;

create table if not exists public.module_data_models (
  module_id text not null,
  model_kind text not null,
  model_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, model_kind, model_name)
);

create table if not exists public.module_data_migrations (
  module_id text primary key,
  data_version integer not null,
  migration_mode text not null,
  migration_dir text not null,
  schema_hash text not null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.module_data_grants (
  module_id text not null,
  grant_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, grant_name)
);

create table if not exists public.module_data_checks (
  module_id text not null,
  check_name text not null,
  schema_hash text not null,
  definition jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (module_id, check_name)
);

insert into public.module_data_migrations
  (module_id, data_version, migration_mode, migration_dir, schema_hash)
values
  ('capability-demo', 1, 'generated', './migrations', 'e3ccbd23fadf13eda61dc24eb7e002c498d517dc5fd3239afe01163d7cb4583a')
on conflict (module_id)
do update set
  data_version = excluded.data_version,
  migration_mode = excluded.migration_mode,
  migration_dir = excluded.migration_dir,
  schema_hash = excluded.schema_hash,
  updated_at = now();

insert into public.module_data_models
  (module_id, model_kind, model_name, schema_hash, definition)
values
  ('capability-demo', 'table', 'demo_notes', '785ab6d88a955a9130a391b1b0eac6393f927f29bd0325053f0332952973f570', '{"name":"demo_notes","physicalName":"mod_capability_demo__demo_notes","scope":"workspace","columns":{"title":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"body":{"kind":"text","nullable":false,"primaryKey":false,"defaultRandom":false},"note_updated_at":{"kind":"timestamp","nullable":true,"primaryKey":false,"defaultRandom":false}},"unique":[],"indexes":[["note_updated_at"]]}'::jsonb)
on conflict (module_id, model_kind, model_name)
do update set
  schema_hash = excluded.schema_hash,
  definition = excluded.definition,
  updated_at = now();

delete from public.module_data_grants where module_id = 'capability-demo';
delete from public.module_data_checks where module_id = 'capability-demo';

create table if not exists public."mod_capability_demo__demo_notes" (
  "id" uuid primary key default gen_random_uuid(),
  "product_id" text not null,
  "module_id" text not null,
  "scope_type" text not null,
  "scope_id" text,
  "created_at" timestamptz not null default now(),
  "updated_at" timestamptz not null default now(),
  "deleted_at" timestamptz,
  "created_by" text,
  "updated_by" text,
  "title" text not null,
  "body" text not null,
  "note_updated_at" timestamptz
);

alter table public."mod_capability_demo__demo_notes" enable row level security;
alter table public."mod_capability_demo__demo_notes" force row level security;

create index if not exists "mod_capability_demo__demo_notes__idx_note_updated_at"
  on public."mod_capability_demo__demo_notes" ("note_updated_at");

drop policy if exists "mod_capability_demo__demo_notes__module_scope_policy" on public."mod_capability_demo__demo_notes";
create policy "mod_capability_demo__demo_notes__module_scope_policy"
  on public."mod_capability_demo__demo_notes"
  for all
  using (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'capability-demo'
    and (
      scope_type = 'public-read'
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  )
  with check (
    product_id = current_setting('ploykit.product_id', true)
    and module_id = 'capability-demo'
    and (
      (
        scope_type = 'public-read'
        and scope_id is null
        and current_setting('ploykit.allow_public_write', true) = 'true'
      )
      or (
        scope_type = current_setting('ploykit.scope_type', true)
        and scope_id = current_setting('ploykit.scope_id', true)
      )
    )
  );
